-- Keep a compact historical snapshot before a provider model is physically removed.
-- The live catalog must not keep upstream-removed models as inactive rows.
CREATE TABLE IF NOT EXISTS ai_model_catalog_archive (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider_id BIGINT UNSIGNED NOT NULL,
  original_model_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  model_type VARCHAR(16) NOT NULL,
  sub_type VARCHAR(32) NOT NULL DEFAULT '',
  api_model_name VARCHAR(64) NOT NULL,
  upstream_model_code VARCHAR(64) NOT NULL DEFAULT '',
  is_async TINYINT(1) NOT NULL DEFAULT 0,
  query_task_url VARCHAR(512) NOT NULL DEFAULT '',
  request_template JSON NOT NULL,
  result_path VARCHAR(128) NOT NULL DEFAULT '',
  status_mapping JSON NOT NULL,
  error_mapping JSON NOT NULL,
  timeout_seconds INT NOT NULL DEFAULT 120,
  retry_times TINYINT NOT NULL DEFAULT 3,
  retry_delay_ms INT NOT NULL DEFAULT 1000,
  daily_limit INT NOT NULL DEFAULT 0,
  daily_limit_per_user INT NOT NULL DEFAULT 0,
  max_concurrency INT NOT NULL DEFAULT 5,
  priority INT NOT NULL DEFAULT 0,
  points_cost INT NOT NULL DEFAULT 0,
  api_cost_cents INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  config JSON NOT NULL,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  archived_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_original_model_id (original_model_id),
  KEY idx_archive_provider_model (provider_id, api_model_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
