-- Seed: video templates from bagege.cn template plaza (30 templates)
-- Categories first, then templates. All idempotent.

INSERT IGNORE INTO template_categories (name, category_key, icon, sort_order, status) VALUES
('时尚视频','fashion_video','',1,'active'),
('电商视频','ecommerce_video','',1,'active'),
('美食视频','food_video','',1,'active'),
('餐厅视频','restaurant_video','',1,'active');

SET @fashion_id = (SELECT id FROM template_categories WHERE category_key='fashion_video' LIMIT 1);
SET @ecommerce_id = (SELECT id FROM template_categories WHERE category_key='ecommerce_video' LIMIT 1);
SET @food_id = (SELECT id FROM template_categories WHERE category_key='food_video' LIMIT 1);
SET @restaurant_id = (SELECT id FROM template_categories WHERE category_key='restaurant_video' LIMIT 1);

INSERT IGNORE INTO templates (title, description, template_type, target_feature, usage_type, source, cover_url, prompt, params_json, ratio, scene, category_id, tags_json, sort_order, is_enabled, visibility, status, review_status, created_at, updated_at) VALUES
('穆斯林风格对镜自拍展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/mirror001.png','A young Malaysian Muslim woman wearing a hijab and elegant modest fashion outfit, standing in front of a large full-length mirror in a modern bedroom. High-quality realistic short video, smooth natural movements, photorealistic details, soft natural indoor lighting with warm tones, 4K resolution, cinematic composition, vertical 9:16 aspect ratio for social media.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',0,1,'public','approved','approved',NOW(3),NOW(3)),
('服装换装转场','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/thumb/yamaxun.png','Suitable for casual and daily wear, match fashionable outfits, Amazon style, create a 15-second skirt fashion transition video. 4K professional full-frame mirrorless camera, studio lighting, clean composition, product close-ups, smooth transition effects.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',1,1,'public','approved','approved',NOW(3),NOW(3)),
('女装卡点快节奏换装展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/002.png','Create a fast-paced clothing showcase video with mirror selfie shots. Models naturally appear, clothing styles, colors and atmosphere are clearly shown. Suitable for recommendation feed conversion. Smooth beat-matched transitions, dynamic camera movements, modern fashion aesthetics.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',2,1,'public','approved','approved',NOW(3),NOW(3)),
('时尚穿搭展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/003.png','Fashion outfit showcase video featuring casual street style looks. Model walking in urban environment, multiple outfit changes with smooth transitions. Natural lighting, vibrant colors, professional fashion photography aesthetics, vertical format for social media.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',3,1,'public','approved','approved',NOW(3),NOW(3)),
('连衣裙展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/004.png','Elegant dress showcase video with model in studio setting. Flowing fabric, graceful movements, detailed close-ups of dress design and patterns. Soft studio lighting, clean white background, professional fashion presentation, 4K quality.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',4,1,'public','approved','approved',NOW(3),NOW(3)),
('鞋子产品展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/005.png','Shoes product showcase video with 360-degree rotation and close-up details. Dynamic lighting highlighting materials and textures. Professional product photography style, smooth camera movements, clean composition. E-commerce ready with space for product information overlay.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',5,1,'public','approved','approved',NOW(3),NOW(3)),
('包包展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/006.png','Luxury handbag showcase video with elegant presentation. Model holding bag in various poses, close-ups of leather texture and hardware details. Studio lighting, clean aesthetic, premium fashion atmosphere, social media vertical format.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',6,1,'public','approved','approved',NOW(3),NOW(3)),
('首饰展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/007.png','Jewelry showcase video featuring necklaces, rings and bracelets. Sparkling close-ups with bokeh effects, model wearing jewelry in elegant settings. Soft golden lighting, luxurious atmosphere, detailed macro shots of gems and precious metals.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',7,1,'public','approved','approved',NOW(3),NOW(3)),
('化妆品展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/008.png','Cosmetics product showcase with elegant presentation. Lipstick, foundation and skincare products displayed with artistic arrangement. Soft feminine color palette, clean minimal aesthetic, beauty brand photography style, suitable for social media marketing.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','fashion',@fashion_id,'[]',8,1,'public','approved','approved',NOW(3),NOW(3)),
('电商产品展示通用','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/009.png','General e-commerce product showcase video. 3D product rotation with modern minimalist background. Clean lighting, professional commercial photography style, suitable for various product categories. Space for brand logo and product information.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','ecommerce',@ecommerce_id,'[]',0,1,'public','approved','approved',NOW(3),NOW(3)),
('美食制作过程展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food001.png','Food preparation and cooking process video. Fresh ingredients being prepared, cooking techniques demonstrated with steam and sizzle effects. Warm kitchen lighting, close-up food shots, appetizing presentation. Professional food photography style with rich colors.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',0,1,'public','approved','approved',NOW(3),NOW(3)),
('甜品展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food002.png','Dessert showcase featuring cakes, pastries and ice cream. Elegant plating with decorative elements, slow-motion pouring and cutting shots. Soft natural lighting, vibrant colors, appetizing close-ups. Perfect for bakery and cafe social media content.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',1,1,'public','approved','approved',NOW(3),NOW(3)),
('饮品展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food003.png','Beverage showcase video featuring coffee, tea and cocktails. Pouring shots with condensation effects, garnishes and colorful liquids. Studio lighting with rim light effects, refreshing summer vibes, professional drink photography for social media.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',2,1,'public','approved','approved',NOW(3),NOW(3)),
('火锅美食展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food004.png','Hot pot feast video with boiling broth, fresh ingredients being dipped. Steam rising with warm atmosphere, colorful vegetables and meats displayed. Traditional Chinese dining aesthetics, appetizing close-ups, social gathering vibe perfect for food content.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',3,1,'public','approved','approved',NOW(3),NOW(3)),
('日料美食展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food005.png','Japanese cuisine showcase featuring sushi, sashimi and ramen. Minimalist presentation with traditional Japanese aesthetics. Clean zen-like composition, natural wood textures, precise knife work close-ups. Premium restaurant photography style.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',4,1,'public','approved','approved',NOW(3),NOW(3)),
('烧烤美食展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food006.png','BBQ and grilled food showcase. Sizzling meat on grill with smoke and fire effects, close-ups of juicy cuts with appetizing glazes. Outdoor cooking atmosphere, golden hour lighting, mouth-watering food presentation for restaurant marketing.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',5,1,'public','approved','approved',NOW(3),NOW(3)),
('烘焙展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food007.png','Bakery and bread making video. Fresh bread coming out of oven, steam and golden crust details. Flour dusting in slow motion, artisanal craftsmanship showcase. Warm rustic atmosphere, bakery shop aesthetics, perfect for pastry shop promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',6,1,'public','approved','approved',NOW(3),NOW(3)),
('海鲜美食展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food008.png','Seafood showcase featuring lobster, crab and fresh fish. Ice bed presentation with garnishes, close-ups of textures and colors. Premium restaurant ambiance, elegant plating, luxury dining photography style suitable for high-end seafood restaurant marketing.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',7,1,'public','approved','approved',NOW(3),NOW(3)),
('中餐美食展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food009.png','Chinese cuisine showcase with wok-fried dishes, steaming dim sum and noodle soups. Dynamic cooking action with flame and wok toss effects. Traditional Chinese restaurant atmosphere, rich colors and textures, authentic food photography for Chinese restaurant promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',8,1,'public','approved','approved',NOW(3),NOW(3)),
('快餐美食展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/food010.png','Fast food showcase featuring burgers, fries and fried chicken. Golden crispy textures with cheese pull effects. Vibrant colors, fun casual dining atmosphere, appetizing close-ups. Modern fast food photography style for delivery platform marketing.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','food',@food_id,'[]',9,1,'public','approved','approved',NOW(3),NOW(3)),
('餐厅环境展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst001.png','Restaurant interior showcase with elegant dining atmosphere. Panning shots of decorated tables, ambient lighting, and architectural details. Warm tones, sophisticated aesthetic, professional interior photography style for restaurant promotion and social media.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',0,1,'public','approved','approved',NOW(3),NOW(3)),
('咖啡厅展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst002.png','Cafe atmosphere showcase with coffee brewing, latte art creation, and cozy interior. Barista at work with espresso machine, steam and pour-over details. Warm afternoon lighting, rustic wooden textures, hipster coffee shop aesthetics perfect for cafe marketing.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',1,1,'public','approved','approved',NOW(3),NOW(3)),
('西餐厅展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst003.png','Fine dining restaurant showcase with candlelit tables, wine pouring and elegant plating. Sophisticated atmosphere with classical music vibe. Premium dining experience aesthetics, romantic ambiance, perfect for upscale restaurant promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',2,1,'public','approved','approved',NOW(3),NOW(3)),
('酒吧展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst004.png','Bar and cocktail lounge showcase with bartender mixing drinks, colorful cocktails with garnishes. Neon lighting atmosphere, ice clinking and pouring sounds visually represented. Trendy nightlife aesthetics, perfect for bar and club social media promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',3,1,'public','approved','approved',NOW(3),NOW(3)),
('自助餐厅展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst005.png','Buffet restaurant showcase with abundant food displays. Panning shots of various cuisine stations, fresh seafood and dessert sections. Bright inviting atmosphere, family-friendly dining aesthetics, colorful food presentations perfect for buffet restaurant advertising.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',4,1,'public','approved','approved',NOW(3),NOW(3)),
('面馆展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst006.png','Noodle shop showcase with hand-pulled noodles being made, steaming broth and fresh toppings. Traditional cooking techniques with dramatic flour effects. Authentic Chinese noodle house atmosphere, warm and inviting, perfect for local restaurant promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',5,1,'public','approved','approved',NOW(3),NOW(3)),
('茶餐厅展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst007.png','Hong Kong style tea restaurant showcase with milk tea pouring, pineapple buns and classic dishes. Retro Hong Kong aesthetics with neon signs and tiled walls. Vibrant casual dining atmosphere, busy kitchen scenes, nostalgic vibes perfect for cha chaan teng promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',6,1,'public','approved','approved',NOW(3),NOW(3)),
('烧烤店展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst008.png','BBQ restaurant showcase with grilling meats on open flame, smoke rising with dramatic lighting effects. Outdoor dining atmosphere with string lights, casual gathering vibe. Appetizing food close-ups, sizzling sounds visually represented, perfect for BBQ joint marketing.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',7,1,'public','approved','approved',NOW(3),NOW(3)),
('火锅店展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst009.png','Hot pot restaurant showcase with boiling spicy broth, ingredients being dipped, steam filling the air. Traditional Sichuan aesthetics with red lanterns and wooden furniture. Social gathering atmosphere, communal dining vibe, perfect for Chinese hot pot restaurant promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',8,1,'public','approved','approved',NOW(3),NOW(3)),
('日料餐厅展示','巴格格模板广场视频模板','video','text_to_video','generate','official','https://shenqitool.site/bagege-ai-kingdom/resources/moban/pic/rst010.png','Japanese restaurant showcase with sushi chef at work, fresh sashimi presentation, and serene interior. Zen garden elements, bamboo and stone textures. Minimalist Japanese aesthetics, peaceful dining atmosphere, perfect for authentic Japanese restaurant promotion.','{"duration":"5s","ratio":"9:16","resolution":"1080p"}','9:16','restaurant',@restaurant_id,'[]',9,1,'public','approved','approved',NOW(3),NOW(3));
