-- Seed WellAPI low-cost pay-per-generation video models.
-- Source checked: https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91 and https://wellapi.ai/api/pricing_new on 2026-05-31.
-- Only quota_type=1 models are seeded here. Time-based quota_type=4 models are intentionally excluded.
-- The API Key is intentionally not stored here. Admin must configure it in the backend UI.

SET @wellapi_provider_exists := (SELECT COUNT(*) FROM ai_model_providers WHERE provider_key = 'wellapi' AND deleted_at IS NULL);

INSERT INTO ai_model_providers
  (name, provider_key, provider_type, api_base_url, api_key, default_timeout, default_retry, remark, status, created_at)
SELECT 'WellAPI', 'wellapi', 'wellapi', 'https://wellapi.ai', '', 600, 3,
       'WellAPI video relay. Seeded models are low-cost quota_type=1 pay-per-generation video models.',
       'active', NOW(3)
WHERE @wellapi_provider_exists = 0;

UPDATE ai_model_providers
   SET name = 'WellAPI',
       provider_type = 'wellapi',
       api_base_url = IF(api_base_url IS NULL OR api_base_url = '', 'https://wellapi.ai', api_base_url),
       default_timeout = GREATEST(default_timeout, 600),
       default_retry = IF(default_retry IS NULL OR default_retry = 0, 3, default_retry),
       remark = 'WellAPI video relay. Seeded models are low-cost quota_type=1 pay-per-generation video models.',
       updated_at = NOW(3)
 WHERE provider_key = 'wellapi' AND deleted_at IS NULL;

SET @wellapi_id := (SELECT id FROM ai_model_providers WHERE provider_key = 'wellapi' AND deleted_at IS NULL LIMIT 1);

DROP TEMPORARY TABLE IF EXISTS tmp_wellapi_video_models;
CREATE TEMPORARY TABLE tmp_wellapi_video_models (
  provider_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  model_type VARCHAR(16) NOT NULL,
  sub_type VARCHAR(32) NOT NULL,
  api_model_name VARCHAR(64) NOT NULL,
  upstream_model_code VARCHAR(64) NOT NULL,
  query_task_url VARCHAR(255) NOT NULL,
  timeout_seconds INT NOT NULL,
  retry_times TINYINT NOT NULL,
  retry_delay_ms INT NOT NULL,
  daily_limit INT NOT NULL,
  daily_limit_per_user INT NOT NULL,
  max_concurrency INT NOT NULL,
  priority INT NOT NULL,
  points_cost INT NOT NULL,
  api_cost_cents INT NOT NULL,
  sort_order INT NOT NULL,
  config_json LONGTEXT NOT NULL,
  remark VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL,
  PRIMARY KEY (provider_id, api_model_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_wellapi_video_models
(provider_id, name, display_name, model_type, sub_type, api_model_name, upstream_model_code, query_task_url, timeout_seconds, retry_times, retry_delay_ms, daily_limit, daily_limit_per_user, max_concurrency, priority, points_cost, api_cost_cents, sort_order, config_json, remark, status)
VALUES
(@wellapi_id, 'WHailuo02Text', 'Hailuo 02 文生视频', 'video', 'text_to_video', 'MiniMax-Hailuo-02:text', 'MiniMax-Hailuo-02', '/minimax/v1/query/video_generation?task_id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6200, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_minimax_video","endpoint_family":"minimax","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["text_to_video"],"default_params":{"duration":"5s","resolution":"768P","prompt_optimizer":true},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/minimax/v1/video_generation","query":"/minimax/v1/query/video_generation?task_id={task_id}","retrieve":"/minimax/v1/files/retrieve?file_id={file_id}"},"description":"Low-cost MiniMax Hailuo 02 pay-per-generation text-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation MiniMax Hailuo 02 text-to-video.', 'active'),
(@wellapi_id, 'WHailuo02Image', 'Hailuo 02 图生视频', 'video', 'image_to_video', 'MiniMax-Hailuo-02:image', 'MiniMax-Hailuo-02', '/minimax/v1/query/video_generation?task_id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6199, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_minimax_video","endpoint_family":"minimax","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"768P","prompt_optimizer":true},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/minimax/v1/video_generation","query":"/minimax/v1/query/video_generation?task_id={task_id}","retrieve":"/minimax/v1/files/retrieve?file_id={file_id}"},"description":"Low-cost MiniMax Hailuo 02 pay-per-generation image-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation MiniMax Hailuo 02 image-to-video.', 'active'),
(@wellapi_id, 'WHailuo02FL', 'Hailuo 02 首尾帧', 'video', 'first_last_frame_video', 'MiniMax-Hailuo-02:first_last', 'MiniMax-Hailuo-02', '/minimax/v1/query/video_generation?task_id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6198, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_minimax_video","endpoint_family":"minimax","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["first_last_frame_video"],"default_params":{"duration":"5s","resolution":"768P","prompt_optimizer":true},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/minimax/v1/video_generation","query":"/minimax/v1/query/video_generation?task_id={task_id}","retrieve":"/minimax/v1/files/retrieve?file_id={file_id}"},"description":"Low-cost MiniMax Hailuo 02 pay-per-generation first-last-frame video via WellAPI."}', 'WellAPI low-cost pay-per-generation MiniMax Hailuo 02 first-last-frame video.', 'active'),
(@wellapi_id, 'WHailuo23Text', 'Hailuo 2.3 文生视频', 'video', 'text_to_video', 'MiniMax-Hailuo-2.3:text', 'MiniMax-Hailuo-2.3', '/minimax/v1/query/video_generation?task_id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6197, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_minimax_video","endpoint_family":"minimax","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["text_to_video"],"default_params":{"duration":"5s","resolution":"768P","prompt_optimizer":true},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/minimax/v1/video_generation","query":"/minimax/v1/query/video_generation?task_id={task_id}","retrieve":"/minimax/v1/files/retrieve?file_id={file_id}"},"description":"Low-cost MiniMax Hailuo 2.3 pay-per-generation text-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation MiniMax Hailuo 2.3 text-to-video.', 'active'),
(@wellapi_id, 'WHailuo23Image', 'Hailuo 2.3 图生视频', 'video', 'image_to_video', 'MiniMax-Hailuo-2.3:image', 'MiniMax-Hailuo-2.3', '/minimax/v1/query/video_generation?task_id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6196, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_minimax_video","endpoint_family":"minimax","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"768P","prompt_optimizer":true},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/minimax/v1/video_generation","query":"/minimax/v1/query/video_generation?task_id={task_id}","retrieve":"/minimax/v1/files/retrieve?file_id={file_id}"},"description":"Low-cost MiniMax Hailuo 2.3 pay-per-generation image-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation MiniMax Hailuo 2.3 image-to-video.', 'active'),
(@wellapi_id, 'WHailuo23FL', 'Hailuo 2.3 首尾帧', 'video', 'first_last_frame_video', 'MiniMax-Hailuo-2.3:first_last', 'MiniMax-Hailuo-2.3', '/minimax/v1/query/video_generation?task_id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6195, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_minimax_video","endpoint_family":"minimax","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["first_last_frame_video"],"default_params":{"duration":"5s","resolution":"768P","prompt_optimizer":true},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/minimax/v1/video_generation","query":"/minimax/v1/query/video_generation?task_id={task_id}","retrieve":"/minimax/v1/files/retrieve?file_id={file_id}"},"description":"Low-cost MiniMax Hailuo 2.3 pay-per-generation first-last-frame video via WellAPI."}', 'WellAPI low-cost pay-per-generation MiniMax Hailuo 2.3 first-last-frame video.', 'active'),
(@wellapi_id, 'WViduQ1ClassicImage', 'Vidu Q1 Classic 图生', 'video', 'image_to_video', 'viduq1-classic:image', 'viduq1-classic', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6194, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/img2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q1 Classic image-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q1 Classic image-to-video.', 'active'),
(@wellapi_id, 'WViduQ1ClassicFL', 'Vidu Q1 Classic 首尾帧', 'video', 'first_last_frame_video', 'viduq1-classic:first_last', 'viduq1-classic', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 5, 2, 6193, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.016,"pricing_note":"WellAPI pricing_new quota_type=1. Rounded api_cost_cents is 2."},"capabilities":["first_last_frame_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/start-end2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q1 Classic first-last-frame video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q1 Classic first-last-frame video.', 'active'),
(@wellapi_id, 'WPixverseV6Text', 'PixVerse V6 文生视频', 'video', 'text_to_video', 'pixverse-video:text', 'pixverse-video', '/openapi/v2/video/result/{task_id}', 600, 3, 5000, 0, 0, 3, 0, 8, 4, 6192, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_pixverse_video","endpoint_family":"pixverse","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.04102,"pricing_note":"WellAPI pricing_new quota_type=1. PixVerse page formula uses model_price 0.014 * 2.93."},"capabilities":["text_to_video"],"default_params":{"duration":"5s","quality":"720p","pixverseModel":"v6"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/openapi/v2/video/text/generate","query":"/openapi/v2/video/result/{task_id}"},"description":"Low-cost PixVerse V6 text-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation PixVerse text-to-video.', 'active'),
(@wellapi_id, 'WPixverseV6Image', 'PixVerse V6 图生视频', 'video', 'image_to_video', 'pixverse-video:image', 'pixverse-video', '/openapi/v2/video/result/{task_id}', 600, 3, 5000, 0, 0, 3, 0, 8, 4, 6191, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_pixverse_video","endpoint_family":"pixverse","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.04102,"pricing_note":"WellAPI pricing_new quota_type=1. PixVerse page formula uses model_price 0.014 * 2.93."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","quality":"720p","pixverseModel":"v6"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/openapi/v2/video/img/generate","upload":"/openapi/v2/image/upload","query":"/openapi/v2/video/result/{task_id}"},"description":"Low-cost PixVerse V6 image-to-video via WellAPI. Image URL is uploaded to PixVerse image id first."}', 'WellAPI low-cost pay-per-generation PixVerse image-to-video.', 'active'),
(@wellapi_id, 'WViduQ2Text', 'Vidu Q2 文生视频', 'video', 'text_to_video', 'viduq2:text', 'viduq2', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 20, 19, 6190, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.1875,"pricing_note":"WellAPI pricing_new quota_type=1. Uses special Vidu group ratio 0.625 in current pricing page."},"capabilities":["text_to_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/text2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q2 text-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q2 text-to-video.', 'active'),
(@wellapi_id, 'WViduQ2Ref', 'Vidu Q2 参考生视频', 'video', 'image_to_video', 'viduq2:reference', 'viduq2', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 20, 19, 6189, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.1875,"pricing_note":"WellAPI pricing_new quota_type=1. Uses special Vidu group ratio 0.625 in current pricing page."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/reference2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q2 reference-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q2 reference-to-video.', 'active'),
(@wellapi_id, 'WViduQ2TurboImage', 'Vidu Q2 Turbo 图生', 'video', 'image_to_video', 'viduq2-turbo:image', 'viduq2-turbo', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 20, 19, 6188, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.1875,"pricing_note":"WellAPI pricing_new quota_type=1. Uses special Vidu group ratio 0.625 in current pricing page."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/img2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q2 Turbo image-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q2 Turbo image-to-video.', 'active'),
(@wellapi_id, 'WViduQ2TurboFL', 'Vidu Q2 Turbo 首尾帧', 'video', 'first_last_frame_video', 'viduq2-turbo:first_last', 'viduq2-turbo', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 20, 19, 6187, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.1875,"pricing_note":"WellAPI pricing_new quota_type=1. Uses special Vidu group ratio 0.625 in current pricing page."},"capabilities":["first_last_frame_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/start-end2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q2 Turbo first-last-frame video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q2 Turbo first-last-frame video.', 'active'),
(@wellapi_id, 'WViduQ2ProRef', 'Vidu Q2 Pro 参考生视频', 'video', 'image_to_video', 'viduq2-pro:reference', 'viduq2-pro', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 28, 25, 6186, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.25,"pricing_note":"WellAPI pricing_new quota_type=1. Uses special Vidu group ratio 0.625 in current pricing page."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/ent/v2/reference2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu Q2 Pro reference-to-video via WellAPI."}', 'WellAPI low-cost pay-per-generation Vidu Q2 Pro reference-to-video.', 'active'),
(@wellapi_id, 'WVidu20Image', 'Vidu 2.0 图生视频', 'video', 'image_to_video', 'vidu2.0:image', 'vidu2.0', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 55, 50, 6185, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.5,"pricing_note":"WellAPI pricing_new quota_type=1."},"capabilities":["image_to_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["360p","720p","1080p"],"endpoints":{"create":"/ent/v2/img2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu 2.0 image-to-video via WellAPI."}', 'WellAPI pay-per-generation Vidu 2.0 image-to-video.', 'active'),
(@wellapi_id, 'WVidu20FL', 'Vidu 2.0 首尾帧', 'video', 'first_last_frame_video', 'vidu2.0:first_last', 'vidu2.0', '/ent/v2/tasks/{task_id}/creations', 600, 3, 5000, 0, 0, 3, 0, 55, 50, 6184, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_vidu_video","endpoint_family":"vidu","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.5,"pricing_note":"WellAPI pricing_new quota_type=1."},"capabilities":["first_last_frame_video"],"default_params":{"duration":"5s","resolution":"720p","movement_amplitude":"auto"},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["360p","720p","1080p"],"endpoints":{"create":"/ent/v2/start-end2video","query":"/ent/v2/tasks/{task_id}/creations"},"description":"Low-cost Vidu 2.0 first-last-frame video via WellAPI."}', 'WellAPI pay-per-generation Vidu 2.0 first-last-frame video.', 'active'),
(@wellapi_id, 'WVeo31FastComponents', 'Veo 3.1 Fast 参考生视频', 'video', 'image_to_video', 'veo3.1-fast-components:image', 'veo3.1-fast-components', '/v1/video/query?id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 40, 36, 6183, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_unified_video","endpoint_family":"unified_video","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.364,"pricing_note":"WellAPI pricing_new quota_type=1. Uses current limited group ratio 1.4."},"capabilities":["image_to_video"],"default_params":{"duration":"8s","aspect_ratio":"16:9","resolution":"720p","enhance_prompt":true,"enable_upsample":false},"supported_ratios":["16:9","9:16","1:1"],"supported_qualities":["720p","1080p","4K"],"endpoints":{"create":"/v1/video/create","query":"/v1/video/query?id={task_id}"},"description":"WellAPI unified video format. Veo 3.1 Fast Components supports up to three reference images."}', 'WellAPI pay-per-generation Veo 3.1 Fast Components reference-to-video.', 'active'),
(@wellapi_id, 'WGrokVideo3Text', 'Grok Video 3 文生视频', 'video', 'text_to_video', 'grok-video-3:text', 'grok-video-3', '/v1/video/query?id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 65, 60, 6182, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_unified_video","endpoint_family":"unified_video","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.6,"pricing_note":"WellAPI pricing_new quota_type=1."},"capabilities":["text_to_video"],"default_params":{"duration":"6s","aspect_ratio":"16:9","size":"720P","enhance_prompt":true},"supported_ratios":["16:9","9:16","3:2"],"supported_qualities":["720P"],"endpoints":{"create":"/v1/video/create","query":"/v1/video/query?id={task_id}"},"description":"WellAPI unified video format. Grok Video 3 6-second pay-per-generation video."}', 'WellAPI pay-per-generation Grok Video 3 text-to-video.', 'active'),
(@wellapi_id, 'WGrokVideo3Image', 'Grok Video 3 图生视频', 'video', 'image_to_video', 'grok-video-3:image', 'grok-video-3', '/v1/video/query?id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 65, 60, 6181, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_unified_video","endpoint_family":"unified_video","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.6,"pricing_note":"WellAPI pricing_new quota_type=1."},"capabilities":["image_to_video"],"default_params":{"duration":"6s","aspect_ratio":"16:9","size":"720P","enhance_prompt":true},"supported_ratios":["16:9","9:16","3:2"],"supported_qualities":["720P"],"endpoints":{"create":"/v1/video/create","query":"/v1/video/query?id={task_id}"},"description":"WellAPI unified video format. Grok Video 3 6-second image-to-video."}', 'WellAPI pay-per-generation Grok Video 3 image-to-video.', 'active'),
(@wellapi_id, 'WGrokVideo310sText', 'Grok Video 3 10s 文生', 'video', 'text_to_video', 'grok-video-3-10s:text', 'grok-video-3-10s', '/v1/video/query?id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 65, 60, 6180, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_unified_video","endpoint_family":"unified_video","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.6,"pricing_note":"WellAPI pricing_new quota_type=1."},"capabilities":["text_to_video"],"default_params":{"duration":"10s","aspect_ratio":"16:9","size":"720P","enhance_prompt":true},"supported_ratios":["16:9","9:16","3:2"],"supported_qualities":["720P"],"endpoints":{"create":"/v1/video/create","query":"/v1/video/query?id={task_id}"},"description":"WellAPI unified video format. Grok Video 3 10-second pay-per-generation video."}', 'WellAPI pay-per-generation Grok Video 3 10-second text-to-video.', 'active'),
(@wellapi_id, 'WGrokVideo310sImage', 'Grok Video 3 10s 图生', 'video', 'image_to_video', 'grok-video-3-10s:image', 'grok-video-3-10s', '/v1/video/query?id={task_id}', 600, 3, 5000, 0, 0, 3, 0, 65, 60, 6179, '{"source":"wellapi_pricing_new","source_url":"https://wellapi.ai/pricing?tag=%E5%8F%82%E8%80%83%E7%94%9F%E8%A7%86%E9%A2%91","source_checked_at":"2026-05-31","api_format":"wellapi_unified_video","endpoint_family":"unified_video","billing":{"quota_type":1,"billing_label":"pay_per_generation","price_yuan":0.6,"pricing_note":"WellAPI pricing_new quota_type=1."},"capabilities":["image_to_video"],"default_params":{"duration":"10s","aspect_ratio":"16:9","size":"720P","enhance_prompt":true},"supported_ratios":["16:9","9:16","3:2"],"supported_qualities":["720P"],"endpoints":{"create":"/v1/video/create","query":"/v1/video/query?id={task_id}"},"description":"WellAPI unified video format. Grok Video 3 10-second image-to-video."}', 'WellAPI pay-per-generation Grok Video 3 10-second image-to-video.', 'active');

UPDATE ai_models m
JOIN tmp_wellapi_video_models s
  ON s.provider_id = m.provider_id
 AND s.api_model_name COLLATE utf8mb4_unicode_ci = m.api_model_name COLLATE utf8mb4_unicode_ci
 AND m.deleted_at IS NULL
   SET m.name = s.name,
       m.display_name = s.display_name,
       m.model_type = s.model_type,
       m.sub_type = s.sub_type,
       m.upstream_model_code = s.upstream_model_code,
       m.is_async = 1,
       m.query_task_url = s.query_task_url,
       m.timeout_seconds = s.timeout_seconds,
       m.retry_times = s.retry_times,
       m.retry_delay_ms = s.retry_delay_ms,
       m.daily_limit = s.daily_limit,
       m.daily_limit_per_user = s.daily_limit_per_user,
       m.max_concurrency = s.max_concurrency,
       m.priority = s.priority,
       m.points_cost = s.points_cost,
       m.api_cost_cents = s.api_cost_cents,
       m.sort_order = s.sort_order,
       m.config = s.config_json,
       m.remark = s.remark,
       m.status = s.status,
       m.updated_at = NOW(3);

INSERT INTO ai_models
(provider_id, name, display_name, model_type, sub_type, api_model_name, upstream_model_code, is_async, query_task_url, request_template, result_path, status_mapping, error_mapping, timeout_seconds, retry_times, retry_delay_ms, daily_limit, daily_limit_per_user, max_concurrency, priority, points_cost, api_cost_cents, sort_order, config, remark, status, created_at, updated_at)
SELECT s.provider_id, s.name, s.display_name, s.model_type, s.sub_type, s.api_model_name, s.upstream_model_code, 1,
       s.query_task_url, '{}', '', '{}', '{}', s.timeout_seconds, s.retry_times, s.retry_delay_ms,
       s.daily_limit, s.daily_limit_per_user, s.max_concurrency, s.priority, s.points_cost, s.api_cost_cents,
       s.sort_order, s.config_json, s.remark, s.status, NOW(3), NOW(3)
  FROM tmp_wellapi_video_models s
 WHERE NOT EXISTS (
   SELECT 1 FROM ai_models m
    WHERE m.provider_id = s.provider_id
      AND m.api_model_name COLLATE utf8mb4_unicode_ci = s.api_model_name COLLATE utf8mb4_unicode_ci
      AND m.deleted_at IS NULL
 );

DROP TEMPORARY TABLE IF EXISTS tmp_wellapi_video_models;
