-- Seed: 巴格格AI (www.bagege.cn) provider + model catalog
-- Source checked: https://www.bagege.cn/api-docs/models-directory on 2026-05-31.
-- The public docs directory loads /v1/frontstage/model-config and exposes 26 video models.
-- The API Key is intentionally not stored here. Admin must configure it in the backend UI.

SET @bagege_provider_exists := (SELECT COUNT(*) FROM ai_model_providers WHERE provider_key = 'bagege' AND deleted_at IS NULL);

INSERT INTO ai_model_providers
  (name, provider_key, provider_type, api_base_url, api_key, default_timeout, default_retry, remark, status, created_at)
SELECT '巴格格AI', 'bagege', 'bagege', 'https://www.bagege.cn', '', 600, 3,
       '巴格格AI OpenAI-compatible async API. Base: /openai/v1; images/videos return tasks and poll /tasks/{id}.',
       'active', NOW(3)
WHERE @bagege_provider_exists = 0;

UPDATE ai_model_providers
   SET name = '巴格格AI',
       provider_type = 'bagege',
       api_base_url = IF(api_base_url IS NULL OR api_base_url = '', 'https://www.bagege.cn', api_base_url),
       default_timeout = GREATEST(default_timeout, 600),
       default_retry = IF(default_retry IS NULL OR default_retry = 0, 3, default_retry),
       remark = '巴格格AI OpenAI-compatible async API. Base: /openai/v1; images/videos return tasks and poll /tasks/{id}.',
       updated_at = NOW(3)
 WHERE provider_key = 'bagege' AND deleted_at IS NULL;

SET @pid := (SELECT id FROM ai_model_providers WHERE provider_key = 'bagege' AND deleted_at IS NULL LIMIT 1);

DROP TEMPORARY TABLE IF EXISTS tmp_bagege_models;
CREATE TEMPORARY TABLE tmp_bagege_models (
  provider_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  model_type VARCHAR(16) NOT NULL,
  sub_type VARCHAR(32) NOT NULL,
  api_model_name VARCHAR(64) NOT NULL,
  upstream_model_code VARCHAR(64) NOT NULL,
  is_async TINYINT(1) NOT NULL,
  timeout_seconds INT NOT NULL,
  retry_times TINYINT NOT NULL,
  retry_delay_ms INT NOT NULL,
  daily_limit INT NOT NULL,
  daily_limit_per_user INT NOT NULL,
  max_concurrency INT NOT NULL,
  priority INT NOT NULL,
  points_cost INT NOT NULL,
  api_cost_cents INT NOT NULL,
  sort_order INT NOT NULL,
  config_json LONGTEXT NOT NULL,
  remark VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL,
  PRIMARY KEY (provider_id, api_model_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_bagege_models
(provider_id, name, display_name, model_type, sub_type, api_model_name, upstream_model_code, is_async, timeout_seconds, retry_times, retry_delay_ms, daily_limit, daily_limit_per_user, max_concurrency, priority, points_cost, api_cost_cents, sort_order, config_json, remark, status)
VALUES
(@pid, 'NanoBanana', 'Nano Banana', 'image', 'text2img', 'bggai-nano-banana-text-to-image-v1', 'bggai-nano-banana-text-to-image-v1', 1, 180, 3, 3000, 0, 0, 5, 0, 6, 6, 1000, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_image"],"supported_modes":["text-to-image"],"fallback_modes":["text-to-image"],"supported_entries":[],"input_keys":["prompt","aspect_ratio","resolution"],"param_names":["prompt","aspect_ratio","resolution"],"channel_key":"","channel_label":"","group_key":"legacy","group_label":"兼容保留","member_accessible":false,"cost":6,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"response_format":"url","size":"1024x1024"},"endpoints":{"create":"/openai/v1/images/generations","edit":"/openai/v1/images/edits","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"Cheapest image generation model. Async polling."}', 'Cheapest image generation model. Async polling.（兼容保留）', 'active'),
(@pid, 'GPTImage2', 'GPT-Image-2', 'image', 'text2img', 'bs-gpt-image-2', 'bs-gpt-image-2', 1, 180, 3, 3000, 0, 0, 5, 0, 12, 12, 999, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"supported_modes":["text-to-image","image-to-image"],"fallback_modes":["text-to-image","image-to-image"],"supported_entries":[],"input_keys":["prompt","aspect_ratio","image_urls"],"param_names":["prompt","aspect_ratio","image_urls"],"channel_key":"","channel_label":"","group_key":"legacy","group_label":"兼容保留","member_accessible":false,"cost":12,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"response_format":"url","size":"1024x1024"},"endpoints":{"create":"/openai/v1/images/generations","edit":"/openai/v1/images/edits","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"High quality image generation model. Supports text-to-image and image-to-image."}', 'High quality image generation model. Supports text-to-image and image-to-image.（兼容保留）', 'active'),
(@pid, '即梦2.0满血(会员专属-标准速度)', '即梦2.0满血(会员专属-标准速度)', 'video', 'text_to_video', 'bggai-seedance-2-0-image-to-video-v1', 'bggai-seedance-2-0-image-to-video-v1', 1, 600, 3, 5000, 0, 0, 5, 0, 220, 220, 5000, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","video_edit"],"supported_modes":["text-to-video","image-to-video","video-to-video"],"fallback_modes":["text-to-video","image-to-video","video-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-text","video-custom-image"],"input_keys":["prompt","image_references","video_url","aspect_ratio","duration","resolution"],"param_names":["prompt","image_references","video_url","aspect_ratio","duration","resolution"],"channel_key":"bggai","channel_label":"BggAI","group_key":"quality","group_label":"追求质量","member_accessible":true,"cost":220,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"文生视频、图生、9图、3视频"}', '文生视频、图生、9图、3视频（追求质量）', 'active'),
(@pid, '可灵KlingO3多参考4K(会员专属)', '可灵KlingO3多参考4K(会员专属)', 'video', 'image_to_video', 'bggai-kling-o3-4k', 'bggai-kling-o3-4k', 1, 600, 3, 5000, 0, 0, 5, 0, 50, 50, 4999, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image","video-custom-text"],"input_keys":["prompt","image_references","aspect_ratio","duration","resolution"],"param_names":["prompt","image_references","aspect_ratio","duration","resolution"],"channel_key":"bggai","channel_label":"BggAI","group_key":"quality","group_label":"追求质量","member_accessible":true,"cost":50,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"支持多图参考生成、图片<=7图"}', '支持多图参考生成、图片<=7图（追求质量）', 'active'),
(@pid, '快乐马文生HappyHorse（官渠）', '快乐马文生HappyHorse（官渠）', 'video', 'text_to_video', '69ef62417f297bdb36eb4288', '69ef62417f297bdb36eb4288', 1, 600, 3, 5000, 0, 0, 5, 0, 250, 250, 4998, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"supported_modes":["text-to-video"],"fallback_modes":["text-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-text"],"input_keys":["enable_safety_checker","resolution","seed","prompt","aspect_ratio","duration"],"param_names":["enable_safety_checker","resolution","seed","prompt","aspect_ratio","duration"],"channel_key":"otoy","channel_label":"OTOY","group_key":"quality","group_label":"追求质量","member_accessible":false,"cost":250,"resolution_cost_overrides":{"720p":250,"1080p":300},"effective_resolution_costs":{"720p":250,"1080p":300},"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持enable_safety_checker、分辨率、提示词等输入能力。"}', '适用于文生视频，重点支持enable_safety_checker、分辨率、提示词等输入能力。（追求质量）', 'active'),
(@pid, '快乐马HappyHorse图生（官渠）', '快乐马HappyHorse图生（官渠）', 'video', 'image_to_video', '69ef62417f297bdb36eb4289', '69ef62417f297bdb36eb4289', 1, 600, 3, 5000, 0, 0, 5, 0, 250, 250, 4997, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image"],"input_keys":["image_url","resolution","enable_safety_checker","seed","prompt","duration"],"param_names":["image_url","resolution","enable_safety_checker","seed","prompt","duration"],"channel_key":"otoy","channel_label":"OTOY","group_key":"quality","group_label":"追求质量","member_accessible":false,"cost":250,"resolution_cost_overrides":{"720p":250,"1080p":300},"effective_resolution_costs":{"720p":250,"1080p":300},"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"图片分辨率>400*400、大小<10M"}', '图片分辨率>400*400、大小<10M（追求质量）', 'active'),
(@pid, 'OmniFlash10s', 'Omni Flash 10s', 'video', 'text_to_video', 'bs-omni_flash-10s', 'bs-omni_flash-10s', 1, 600, 3, 5000, 0, 0, 5, 0, 100, 100, 4996, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image","video-custom-text"],"input_keys":["prompt","image_urls","aspect_ratio"],"param_names":["prompt","image_urls","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"quality","group_label":"追求质量","member_accessible":false,"cost":100,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生、首尾帧、7图"}', '适用于文生、首尾帧、7图（追求质量）', 'active'),
(@pid, '快乐马HappyHorse视频参考（官渠）', '快乐马HappyHorse视频参考（官渠）', 'video', 'video_edit', '69ef62417f297bdb36eb428b', '69ef62417f297bdb36eb428b', 1, 600, 3, 5000, 0, 0, 5, 0, 250, 250, 4995, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["video_edit"],"supported_modes":["video-to-video"],"fallback_modes":["video-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","prompt-reverse-video","video-custom-video"],"input_keys":["enable_safety_checker","resolution","audio_setting","seed","video_url","prompt","reference_image_urls"],"param_names":["enable_safety_checker","resolution","audio_setting","seed","video_url","prompt","reference_image_urls"],"channel_key":"otoy","channel_label":"OTOY","group_key":"quality","group_label":"追求质量","member_accessible":false,"cost":250,"resolution_cost_overrides":{"720p":250,"1080p":300},"effective_resolution_costs":{"720p":250,"1080p":300},"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"视频大小<=100M、<=15秒、参考图<=5、图片大小<=10M"}', '视频大小<=100M、<=15秒、参考图<=5、图片大小<=10M（追求质量）', 'active'),
(@pid, 'Pixverse C1多图参考官渠', 'Pixverse C1多图参考官渠', 'video', 'image_to_video', '69d8f8f3536058ca96b2511d', '69d8f8f3536058ca96b2511d', 1, 600, 3, 5000, 0, 0, 5, 0, 60, 60, 4994, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image"],"input_keys":["aspect_ratio","seed","generate_audio_switch","prompt","resolution","image_references","duration"],"param_names":["aspect_ratio","seed","generate_audio_switch","prompt","resolution","image_references","duration"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":60,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"世界第三、最高支持7张图、图片<4000*4000适用短剧、电影"}', '世界第三、最高支持7张图、图片<4000*4000适用短剧、电影（性价比）', 'active'),
(@pid, 'Pix拍我V6-图生视频（官渠）', 'Pix拍我V6-图生视频（官渠）', 'video', 'image_to_video', '69caccde8d85da2436705a83', '69caccde8d85da2436705a83', 1, 600, 3, 5000, 0, 0, 5, 0, 50, 50, 4993, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image"],"input_keys":["thinking_type","prompt","generate_audio_switch","resolution","style","duration","negative_prompt","generate_multi_clip_switch","image_url","seed"],"param_names":["thinking_type","prompt","generate_audio_switch","resolution","style","duration","negative_prompt","generate_multi_clip_switch","image_url","seed"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":50,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"现世界第三、仅次于2.0、小马"}', '现世界第三、仅次于2.0、小马（性价比）', 'active'),
(@pid, '拍我V6视频参考（官渠）', '拍我V6视频参考（官渠）', 'video', 'video_edit', '69caccde8d85da2436705a82', '69caccde8d85da2436705a82', 1, 600, 3, 5000, 0, 0, 5, 0, 50, 50, 4992, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["video_edit"],"supported_modes":["video-to-video"],"fallback_modes":["video-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","prompt-reverse-video","video-custom-video"],"input_keys":["prompt","generate_audio_switch","video_url","resolution","style","negative_prompt","duration","seed"],"param_names":["prompt","generate_audio_switch","video_url","resolution","style","negative_prompt","duration","seed"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":50,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于视频参考，重点支持提示词、generate_audio_switch、输入视频等输入能力。"}', '适用于视频参考，重点支持提示词、generate_audio_switch、输入视频等输入能力。（性价比）', 'active'),
(@pid, '可灵2.6运动控制（官渠）', '可灵2.6运动控制（官渠）', 'video', 'video_edit', '6949a3c005d72eaff1d78b9c', '6949a3c005d72eaff1d78b9c', 1, 600, 3, 5000, 0, 0, 5, 0, 100, 100, 4991, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["video_edit"],"supported_modes":["video-to-video"],"fallback_modes":["video-to-video"],"supported_entries":["prompt-reverse-video","video-custom-video"],"input_keys":["prompt","video_url","character_orientation","keep_original_sound","image_url"],"param_names":["prompt","video_url","character_orientation","keep_original_sound","image_url"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":100,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于视频参考，重点支持提示词、输入视频、character_orientation等输入能力。"}', '适用于视频参考，重点支持提示词、输入视频、character_orientation等输入能力。（性价比）', 'active'),
(@pid, '拍我Pixverse v6文生视频（官渠）', '拍我Pixverse v6文生视频（官渠）', 'video', 'text_to_video', '69caccde8d85da2436705a80', '69caccde8d85da2436705a80', 1, 600, 3, 5000, 0, 0, 5, 0, 50, 50, 4990, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"supported_modes":["text-to-video"],"fallback_modes":["text-to-video"],"supported_entries":["video-custom-text","ecommerce-marketing","real-person-video","comic-video"],"input_keys":["thinking_type","prompt","aspect_ratio","generate_audio_switch","resolution","style","duration","negative_prompt","generate_multi_clip_switch","seed"],"param_names":["thinking_type","prompt","aspect_ratio","generate_audio_switch","resolution","style","duration","negative_prompt","generate_multi_clip_switch","seed"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":50,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持thinking_type、提示词、画面比例等输入能力。"}', '适用于文生视频，重点支持thinking_type、提示词、画面比例等输入能力。（性价比）', 'active'),
(@pid, 'Pixverse c1图生视频（官渠）', 'Pixverse c1图生视频（官渠）', 'video', 'image_to_video', '69d8f8f3536058ca96b2511c', '69d8f8f3536058ca96b2511c', 1, 600, 3, 5000, 0, 0, 5, 0, 55, 55, 4989, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["video-custom-image","ecommerce-marketing","real-person-video","comic-video"],"input_keys":["generate_audio_switch","seed","image_url","prompt","resolution","duration"],"param_names":["generate_audio_switch","seed","image_url","prompt","resolution","duration"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":55,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于图生视频，重点支持generate_audio_switch、输入图片、提示词等输入能力。"}', '适用于图生视频，重点支持generate_audio_switch、输入图片、提示词等输入能力。（性价比）', 'active'),
(@pid, '阿里Wan v2.7 (多图参考官渠）', '阿里Wan v2.7 (多图参考官渠）', 'video', 'image_to_video', '69cf6db0be114d8b9b54d249', '69cf6db0be114d8b9b54d249', 1, 600, 3, 5000, 0, 0, 5, 0, 150, 150, 4988, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","prompt-reverse-video","video-custom-text","video-custom-image"],"input_keys":["prompt","aspect_ratio","resolution","duration","reference_video_urls","reference_image_urls","seed","multi_shots","negative_prompt","enable_safety_checker"],"param_names":["prompt","aspect_ratio","resolution","duration","reference_video_urls","reference_image_urls","seed","multi_shots","negative_prompt","enable_safety_checker"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":150,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"支持多图视频参考、总量<=5"}', '支持多图视频参考、总量<=5（性价比）', 'active'),
(@pid, '阿里Wan v2.7图生视频（官渠）', '阿里Wan v2.7图生视频（官渠）', 'video', 'image_to_video', '69cf6db0be114d8b9b54d248', '69cf6db0be114d8b9b54d248', 1, 600, 3, 5000, 0, 0, 5, 0, 150, 150, 4987, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video","first_last_frame_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image"],"input_keys":["audio_url","resolution","prompt","negative_prompt","image_url","video_url","end_image_url","enable_prompt_expansion","seed","duration","enable_safety_checker"],"param_names":["audio_url","resolution","prompt","negative_prompt","image_url","video_url","end_image_url","enable_prompt_expansion","seed","duration","enable_safety_checker"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":150,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于图生视频，重点支持输入音频、分辨率、提示词等输入能力。"}', '适用于图生视频，重点支持输入音频、分辨率、提示词等输入能力。（性价比）', 'active'),
(@pid, '拍我Pixverse v6 (转场过渡官渠）', '拍我Pixverse v6 (转场过渡官渠）', 'video', 'first_last_frame_video', '69caccde8d85da2436705a81', '69caccde8d85da2436705a81', 1, 600, 3, 5000, 0, 0, 5, 0, 50, 50, 4986, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video","first_last_frame_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["video-custom-image","ecommerce-marketing","real-person-video","comic-video"],"input_keys":["thinking_type","end_image_url","aspect_ratio","prompt","resolution","generate_audio_switch","first_image_url","duration","negative_prompt","generate_multi_clip_switch","style","seed"],"param_names":["thinking_type","end_image_url","aspect_ratio","prompt","resolution","generate_audio_switch","first_image_url","duration","negative_prompt","generate_multi_clip_switch","style","seed"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":50,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于多图片平滑过渡转场效果"}', '适用于多图片平滑过渡转场效果（性价比）', 'active'),
(@pid, 'Wan v2.7 (视频参考)官渠', 'Wan v2.7 (视频参考)官渠', 'video', 'video_edit', '69cf6db0be114d8b9b54d24a', '69cf6db0be114d8b9b54d24a', 1, 600, 3, 5000, 0, 0, 5, 0, 150, 150, 4985, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["video_edit"],"supported_modes":["video-to-video"],"fallback_modes":["video-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","prompt-reverse-video","video-custom-video"],"input_keys":["prompt","video_url","aspect_ratio","duration","reference_image_url","resolution","enable_safety_checker","seed","audio_setting"],"param_names":["prompt","video_url","aspect_ratio","duration","reference_image_url","resolution","enable_safety_checker","seed","audio_setting"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":150,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于视频参考，重点支持提示词、输入视频、画面比例等输入能力。"}', '适用于视频参考，重点支持提示词、输入视频、画面比例等输入能力。（性价比）', 'active'),
(@pid, 'LTXv2.3首尾帧', 'LTXv2.3首尾帧', 'video', 'first_last_frame_video', '69aa908f527fafdeb1464a7d', '69aa908f527fafdeb1464a7d', 1, 600, 3, 5000, 0, 0, 5, 0, 70, 70, 4984, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video","first_last_frame_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["video-custom-image"],"input_keys":["prompt","duration","resolution","generate_audio","aspect_ratio","image_url","fps","end_image_url"],"param_names":["prompt","duration","resolution","generate_audio","aspect_ratio","image_url","fps","end_image_url"],"channel_key":"otoy","channel_label":"OTOY","group_key":"balanced","group_label":"性价比","member_accessible":false,"cost":70,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于图生视频，重点支持提示词、时长、分辨率等输入能力。"}', '适用于图生视频，重点支持提示词、时长、分辨率等输入能力。（性价比）', 'active'),
(@pid, 'Veo31Fast', 'Veo 3.1 Fast', 'video', 'text_to_video', 'bs-veo_3_1-fast', 'bs-veo_3_1-fast', 1, 600, 3, 5000, 0, 0, 5, 0, 20, 20, 4983, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["video-custom-text","video-custom-image"],"input_keys":["prompt","start_image_url","end_image_url","aspect_ratio"],"param_names":["prompt","start_image_url","end_image_url","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":20,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。"}', '适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。（实验模型）', 'active'),
(@pid, 'Veo31FastFL', 'Veo 3.1 Fast FL', 'video', 'image_to_video', 'bs-veo_3_1-fast-fl', 'bs-veo_3_1-fast-fl', 1, 600, 3, 5000, 0, 0, 5, 0, 20, 20, 4982, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["video-custom-image","video-custom-text"],"input_keys":["prompt","start_image_url","end_image_url","aspect_ratio"],"param_names":["prompt","start_image_url","end_image_url","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":20,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。"}', '适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。（实验模型）', 'active'),
(@pid, 'Veo31FastFLHD', 'Veo 3.1 Fast FL HD', 'video', 'first_last_frame_video', 'bs-veo_3_1-fast-fl-hd', 'bs-veo_3_1-fast-fl-hd', 1, 600, 3, 5000, 0, 0, 5, 0, 30, 30, 4981, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image","video-custom-text"],"input_keys":["prompt","start_image_url","end_image_url","aspect_ratio"],"param_names":["prompt","start_image_url","end_image_url","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":30,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。"}', '适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。（实验模型）', 'active'),
(@pid, 'Veo 3.1 Fast高质量', 'Veo 3.1 Fast高质量', 'video', 'text_to_video', 'bs-veo_3_1-fast-hd', 'bs-veo_3_1-fast-hd', 1, 600, 3, 5000, 0, 0, 5, 0, 30, 30, 4980, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-text","video-custom-image"],"input_keys":["prompt","start_image_url","end_image_url","aspect_ratio"],"param_names":["prompt","start_image_url","end_image_url","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":30,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。"}', '适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。（实验模型）', 'active'),
(@pid, 'Veo 3.1高质量首尾帧&文生', 'Veo 3.1高质量首尾帧&文生', 'video', 'first_last_frame_video', 'bs-veo_3_1-hd-fl', 'bs-veo_3_1-hd-fl', 1, 600, 3, 5000, 0, 0, 5, 0, 30, 30, 4979, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["video-custom-image","video-custom-text"],"input_keys":["prompt","start_image_url","end_image_url","aspect_ratio"],"param_names":["prompt","start_image_url","end_image_url","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":30,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。"}', '适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。（实验模型）', 'active'),
(@pid, 'Veo 3.1 首尾帧&文生', 'Veo 3.1 首尾帧&文生', 'video', 'first_last_frame_video', 'bs-veo_3_1-fl', 'bs-veo_3_1-fl', 1, 600, 3, 5000, 0, 0, 5, 0, 20, 20, 4978, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"supported_modes":["text-to-video","image-to-video"],"fallback_modes":["text-to-video","image-to-video"],"supported_entries":["video-custom-text","video-custom-image"],"input_keys":["prompt","start_image_url","end_image_url","aspect_ratio"],"param_names":["prompt","start_image_url","end_image_url","aspect_ratio"],"channel_key":"bs","channel_label":"BS API","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":20,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。"}', '适用于文生视频，重点支持提示词、起始帧、结束帧等输入能力。（实验模型）', 'active'),
(@pid, 'Wan v2.6 图生支持音频', 'Wan v2.6 图生支持音频', 'video', 'image_to_video', '696e8fd08f8f9f2700aec99a', '696e8fd08f8f9f2700aec99a', 1, 600, 3, 5000, 0, 0, 5, 0, 78, 78, 4977, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","video-custom-image","comic-video"],"input_keys":["prompt","resolution","duration","audio_url","image_url","enable_prompt_expansion","seed","multi_shots","negative_prompt","enable_safety_checker"],"param_names":["prompt","resolution","duration","audio_url","image_url","enable_prompt_expansion","seed","multi_shots","negative_prompt","enable_safety_checker"],"channel_key":"otoy","channel_label":"OTOY","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":78,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"支持1张图、1个音频"}', '支持1张图、1个音频（实验模型）', 'active'),
(@pid, 'Grok多图生视频（官方）', 'Grok多图生视频（官方）', 'video', 'image_to_video', '69c337afdb54532669e3af4a', '69c337afdb54532669e3af4a', 1, 600, 3, 5000, 0, 0, 5, 0, 77, 77, 4976, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"supported_modes":["image-to-video"],"fallback_modes":["image-to-video"],"supported_entries":["ecommerce-marketing","real-person-video","comic-video","video-custom-image"],"input_keys":["prompt","aspect_ratio","resolution","reference_image_urls","duration"],"param_names":["prompt","aspect_ratio","resolution","reference_image_urls","duration"],"channel_key":"otoy","channel_label":"OTOY","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":77,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"Grok最新模型、支持最多7张图"}', 'Grok最新模型、支持最多7张图（实验模型）', 'active'),
(@pid, 'Grok视频参考（官方）', 'Grok视频参考（官方）', 'video', 'video_edit', '69c337afdb54532669e3af49', '69c337afdb54532669e3af49', 1, 600, 3, 5000, 0, 0, 5, 0, 75, 75, 4975, '{"source":"bagege_api_docs_models_directory","source_url":"https://www.bagege.cn/api-docs/models-directory","source_checked_at":"2026-05-31","capabilities":["video_edit"],"supported_modes":["video-to-video"],"fallback_modes":["video-to-video"],"supported_entries":["video-custom-video"],"input_keys":["prompt","video_url","duration"],"param_names":["prompt","video_url","duration"],"channel_key":"otoy","channel_label":"OTOY","group_key":"experimental","group_label":"实验模型","member_accessible":false,"cost":75,"resolution_cost_overrides":null,"effective_resolution_costs":null,"max_polling_minutes":120,"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"endpoints":{"create":"/openai/v1/videos/generations","query":"/openai/v1/tasks/{task_id}"},"api_format":"bagege_openai_async","description":"适用于视频参考，重点支持提示词、输入视频、时长等输入能力。"}', '适用于视频参考，重点支持提示词、输入视频、时长等输入能力。（实验模型）', 'active');

UPDATE ai_models m
JOIN tmp_bagege_models s
  ON s.provider_id = m.provider_id
 AND s.api_model_name COLLATE utf8mb4_unicode_ci = m.api_model_name COLLATE utf8mb4_unicode_ci
 AND m.deleted_at IS NULL
   SET m.name = s.name,
       m.display_name = s.display_name,
       m.model_type = s.model_type,
       m.sub_type = s.sub_type,
       m.upstream_model_code = s.upstream_model_code,
       m.is_async = s.is_async,
       m.timeout_seconds = s.timeout_seconds,
       m.retry_times = s.retry_times,
       m.retry_delay_ms = s.retry_delay_ms,
       m.max_concurrency = s.max_concurrency,
       m.priority = s.priority,
       m.points_cost = s.points_cost,
       m.api_cost_cents = s.api_cost_cents,
       m.sort_order = s.sort_order,
       m.config = s.config_json,
       m.remark = s.remark,
       m.status = s.status,
       m.updated_at = NOW(3);

INSERT INTO ai_models
(provider_id, name, display_name, model_type, sub_type, api_model_name, upstream_model_code, is_async, query_task_url, request_template, result_path, status_mapping, error_mapping, timeout_seconds, retry_times, retry_delay_ms, daily_limit, daily_limit_per_user, max_concurrency, priority, points_cost, api_cost_cents, sort_order, config, remark, status, created_at, updated_at)
SELECT s.provider_id, s.name, s.display_name, s.model_type, s.sub_type, s.api_model_name, s.upstream_model_code, s.is_async,
       '/openai/v1/tasks/{task_id}', '{}', '', '{}', '{}', s.timeout_seconds, s.retry_times, s.retry_delay_ms,
       s.daily_limit, s.daily_limit_per_user, s.max_concurrency, s.priority, s.points_cost, s.api_cost_cents,
       s.sort_order, s.config_json, s.remark, s.status, NOW(3), NOW(3)
  FROM tmp_bagege_models s
 WHERE NOT EXISTS (
   SELECT 1 FROM ai_models m
    WHERE m.provider_id = s.provider_id
      AND m.api_model_name COLLATE utf8mb4_unicode_ci = s.api_model_name COLLATE utf8mb4_unicode_ci
      AND m.deleted_at IS NULL
 );

DROP TEMPORARY TABLE IF EXISTS tmp_bagege_models;
