-- Seed additional Chinese and English content-compliance words.
INSERT IGNORE INTO content_sensitive_words (word) VALUES
('毒品交易'),
('贩毒'),
('吸毒'),
('制毒'),
('大麻'),
('冰毒'),
('海洛因'),
('枪支交易'),
('买枪'),
('卖枪'),
('弹药'),
('爆炸物'),
('炸弹'),
('诈骗'),
('钓鱼网站'),
('洗钱'),
('银行卡买卖'),
('身份证买卖'),
('发票代开'),
('假证'),
('色情'),
('裸露'),
('未成年人色情'),
('儿童色情'),
('暴力血腥'),
('自残'),
('自杀'),
('仇恨言论'),
('种族歧视'),
('drug trafficking'),
('illegal drugs'),
('cocaine'),
('heroin'),
('methamphetamine'),
('marijuana sale'),
('weapon sale'),
('gun sale'),
('buy a gun'),
('ammunition sale'),
('explosives'),
('bomb making'),
('phishing'),
('money laundering'),
('credit card fraud'),
('identity theft'),
('fake invoice'),
('fake id'),
('pornography'),
('child sexual abuse'),
('minor sexual content'),
('graphic violence'),
('self harm'),
('suicide method'),
('hate speech'),
('racial slur');
