-- Seed: 小马AI API provider and model catalog
-- Source checked: https://api.lk888.ai/v1/skills/models?type=image|video|audio|chat on 2026-05-31.
-- The API Key is intentionally not stored here. Admin must configure it in the backend UI.

SET @xiaoma_provider_exists := (SELECT COUNT(*) FROM ai_model_providers WHERE provider_key = 'xiaoma' AND deleted_at IS NULL);

INSERT INTO ai_model_providers
  (name, provider_key, provider_type, api_base_url, api_key, default_timeout, default_retry, remark, status, created_at)
SELECT '小马AI', 'xiaoma', 'xiaoma', 'https://api.lk888.ai', '', 600, 3,
       '小马AI API。支持图片、视频、音频、聊天模型；媒体协议 /v1/media/generate + /v1/media/status，聊天模型按官方兼容协议透传。',
       'active', NOW(3)
WHERE @xiaoma_provider_exists = 0;

UPDATE ai_model_providers
   SET name = '小马AI',
       provider_type = 'xiaoma',
       api_base_url = IF(api_base_url IS NULL OR api_base_url = '', 'https://api.lk888.ai', api_base_url),
       default_timeout = GREATEST(default_timeout, 600),
       default_retry = IF(default_retry IS NULL OR default_retry = 0, 3, default_retry),
       remark = '小马AI API。支持图片、视频、音频、聊天模型；媒体协议 /v1/media/generate + /v1/media/status，聊天模型按官方兼容协议透传。',
       updated_at = NOW(3)
 WHERE provider_key = 'xiaoma' AND deleted_at IS NULL;

SET @xiaoma_id := (SELECT id FROM ai_model_providers WHERE provider_key = 'xiaoma' AND deleted_at IS NULL LIMIT 1);

DROP TEMPORARY TABLE IF EXISTS tmp_xiaoma_api_models;
CREATE TEMPORARY TABLE tmp_xiaoma_api_models (
  provider_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  model_type VARCHAR(16) NOT NULL,
  sub_type VARCHAR(32) NOT NULL,
  api_model_name VARCHAR(64) NOT NULL,
  upstream_model_code VARCHAR(64) NOT NULL,
  is_async TINYINT(1) NOT NULL,
  timeout_seconds INT NOT NULL,
  retry_times TINYINT NOT NULL,
  retry_delay_ms INT NOT NULL,
  daily_limit INT NOT NULL,
  daily_limit_per_user INT NOT NULL,
  max_concurrency INT NOT NULL,
  priority INT NOT NULL,
  points_cost INT NOT NULL,
  api_cost_cents INT NOT NULL,
  sort_order INT NOT NULL,
  config_json LONGTEXT NOT NULL,
  remark VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL,
  PRIMARY KEY (provider_id, api_model_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_xiaoma_api_models
(provider_id, name, display_name, model_type, sub_type, api_model_name, upstream_model_code, is_async, timeout_seconds, retry_times, retry_delay_ms, daily_limit, daily_limit_per_user, max_concurrency, priority, points_cost, api_cost_cents, sort_order, config_json, remark, status)
VALUES
(@xiaoma_id, 'gpt-image-2', 'GPT Image 2', 'image', 'image_to_image', 'gpt-image-2', 'gpt-image-2', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 5000, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","aspect_ratio","resolution","size","quality","n","response_format"],"supported_ratios":["1:1"],"supported_qualities":["1K","auto","high","medium","low"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"GPT Image 2 is an OpenAI image generation model for text-to-image creation, reference-image editing, accurate visual composition, and high-quality rendering."}', 'GPT Image 2 is an OpenAI image generation model for text-to-image creation, reference-image editing, accurate visual composition, and high-quality rendering.', 'active'),
(@xiaoma_id, 'gemini-3-pro-image-preview', 'Nano Banana Pro', 'image', 'image_to_image', 'gemini-3-pro-image-preview', 'gemini-3-pro-image-preview', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4999, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["AI feature"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","aspectRatio","imageSize"],"supported_ratios":["auto","1:1","2:3","3:2","3:4","4:3","4:5","5:4","9:16","16:9","21:9"],"supported_qualities":["1K","2K","4K"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Nano Banana Pro is a Google image generation and editing model with strong prompt understanding, reference-image support, and high-resolution output."}', 'Nano Banana Pro is a Google image generation and editing model with strong prompt understanding, reference-image support, and high-resolution output.', 'active'),
(@xiaoma_id, 'gemini-3.1-flash-image-preview', 'Nano Banana 2', 'image', 'image_to_image', 'gemini-3.1-flash-image-preview', 'gemini-3.1-flash-image-preview', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4998, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["AI feature"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","aspectRatio","imageSize","web_search","thinkingLevel"],"supported_ratios":["auto","1:1","2:3","3:2","3:4","4:3","4:5","5:4","9:16","16:9","21:9","1:4","4:1","1:8","8:1"],"supported_qualities":["0.5K","1K","2K","4K"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Nano Banana 2 is a Google image generation and editing model with strong prompt understanding, reference-image support, and high-resolution output."}', 'Nano Banana 2 is a Google image generation and editing model with strong prompt understanding, reference-image support, and high-resolution output.', 'active'),
(@xiaoma_id, 'gpt-image-2-guan', 'GPT Image 2 Official', 'image', 'image_to_image', 'gpt-image-2-guan', 'gpt-image-2-guan', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4997, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size","quality"],"supported_ratios":[],"supported_qualities":["auto","high","medium","low"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"GPT Image 2 Official is an OpenAI image generation model for text-to-image creation, reference-image editing, accurate visual composition, and high-quality rendering."}', 'GPT Image 2 Official is an OpenAI image generation model for text-to-image creation, reference-image editing, accurate visual composition, and high-quality rendering.', 'active'),
(@xiaoma_id, 'vidu-image-2', 'VIDU Iamge 2', 'image', 'image_to_image', 'vidu-image-2', 'vidu-image-2', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4996, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["AI feature"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","aspect_ratio","resolution","quality","style"],"supported_ratios":["16:9","9:16","1:1","4:3","3:4","3:2","2:3","5:4","4:5","7:3"],"supported_qualities":["1K","2K","3K","low","medium","high"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"VIDU Iamge 2 is a Vidu image model for text-to-image generation, multi-image reference, and image editing with adjustable quality and aspect ratio."}', 'VIDU Iamge 2 is a Vidu image model for text-to-image generation, multi-image reference, and image editing with adjustable quality and aspect ratio.', 'active'),
(@xiaoma_id, 'doubao-seedream-5-0-260128', 'Seedream 5.0', 'image', 'image_to_image', 'doubao-seedream-5-0-260128', 'doubao-seedream-5-0-260128', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4995, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image","Multi-image fusion","Web-search image generation","3k","Seedream"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size","aspect_ratio","web_search"],"supported_ratios":["auto","1:1","4:3","3:4","16:9","9:16","3:2","2:3","21:9"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Seedream 5.0 is a ByteDance Seedream image model for text-to-image generation, image editing, multi-image fusion, and high-resolution visual creation."}', 'Seedream 5.0 is a ByteDance Seedream image model for text-to-image generation, image editing, multi-image fusion, and high-resolution visual creation.', 'active'),
(@xiaoma_id, 'doubao-seedream-4-5-251128', 'Seedream 4.5', 'image', 'image_to_image', 'doubao-seedream-4-5-251128', 'doubao-seedream-4-5-251128', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4994, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size","aspect_ratio"],"supported_ratios":["auto","1:1","4:3","3:4","16:9","9:16","3:2","2:3","21:9"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Seedream 4.5 is a ByteDance Seedream image model for text-to-image generation, image editing, multi-image fusion, and high-resolution visual creation."}', 'Seedream 4.5 is a ByteDance Seedream image model for text-to-image generation, image editing, multi-image fusion, and high-resolution visual creation.', 'active'),
(@xiaoma_id, 'mj_imagine', 'Midjourney', 'image', 'image_to_image', 'mj_imagine', 'mj_imagine', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4993, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","botType","aspectRatio","quality","stylize","chaos","style"],"supported_ratios":["1:1","16:9","9:16","4:3","3:4","3:2","2:3","4:5","5:4","21:9"],"supported_qualities":["0.25","0.5","1","2"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Midjourney is an AI image generation model known for artistic style, concept art, illustration, posters, and high-quality visual design."}', 'Midjourney is an AI image generation model known for artistic style, concept art, illustration, posters, and high-quality visual design.', 'active'),
(@xiaoma_id, 'wan2.7-image', 'Wanxiang 2.7 Image', 'image', 'image_to_image', 'wan2.7-image', 'wan2.7-image', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4992, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","quality","size"],"supported_ratios":[],"supported_qualities":["standard","pro"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"wan2.7-image is an AI image model for generation, editing, reference-image workflows, and high-quality visual creation."}', 'wan2.7-image is an AI image model for generation, editing, reference-image workflows, and high-quality visual creation.', 'active'),
(@xiaoma_id, 'grok-4.2-image', 'grok-4.2-image', 'image', 'image_to_image', 'grok-4.2-image', 'grok-4.2-image', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4991, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"grok-4.2-image is an xAI image generation model for text-to-image creation and image editing with multiple output sizes."}', 'grok-4.2-image is an xAI image generation model for text-to-image creation and image editing with multiple output sizes.', 'active'),
(@xiaoma_id, 'kling-v3-omni', 'Kling-V3-Omni', 'image', 'image_to_image', 'kling-v3-omni', 'kling-v3-omni', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4990, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image","Multi-image fusion","4k","HD"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","resolution","aspect_ratio"],"supported_ratios":["auto","16:9","9:16","1:1","4:3","3:4","3:2","2:3","21:9"],"supported_qualities":["1k","2k","4k"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-V3-Omni is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-V3-Omni is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'grok-4.1-image', 'grok-4.1-image', 'image', 'image_to_image', 'grok-4.1-image', 'grok-4.1-image', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4989, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"grok-4.1-image is an xAI image generation model for text-to-image creation and image editing with multiple output sizes."}', 'grok-4.1-image is an xAI image generation model for text-to-image creation and image editing with multiple output sizes.', 'active'),
(@xiaoma_id, 'qwen-image', 'Qwen-image-max', 'image', 'image_edit', 'qwen-image', 'qwen-image', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4988, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image","image_edit"],"tags":["Text-to-image","Image editing","Multi-image fusion"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size","prompt_extend"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Qwen-image-max is a Qwen image model for text-to-image creation, image editing, complex text rendering, and multi-image reference workflows."}', 'Qwen-image-max is a Qwen image model for text-to-image creation, image editing, complex text rendering, and multi-image reference workflows.', 'active'),
(@xiaoma_id, 'kling-v3', 'Kling-V3', 'image', 'image_to_image', 'kling-v3', 'kling-v3', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4987, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image","HD"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","resolution","aspect_ratio"],"supported_ratios":["auto","16:9","9:16","1:1","4:3","3:4","3:2","2:3","21:9"],"supported_qualities":["2k","1k"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-V3 is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-V3 is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'wan2.6-image', 'Wanxiang 2.6 Image', 'image', 'image_to_image', 'wan2.6-image', 'wan2.6-image', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4986, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","size","prompt_extend"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"wan2.6-image is an AI image model for generation, editing, reference-image workflows, and high-quality visual creation."}', 'wan2.6-image is an AI image model for generation, editing, reference-image workflows, and high-quality visual creation.', 'active'),
(@xiaoma_id, 'kling-image-o1', 'Kling o1', 'image', 'image_to_image', 'kling-image-o1', 'kling-image-o1', 1, 180, 3, 1000, 0, 0, 5, 0, 2, 0, 4985, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_image","image_to_image"],"tags":["Text-to-image","Image-to-image"],"default_params":{"resolution":"1k","aspect_ratio":"1:1"},"param_names":["prompt","images","aspect_ratio","resolution"],"supported_ratios":["auto","16:9","9:16","1:1","4:3","3:4","3:2","2:3","21:9"],"supported_qualities":["2k","1k"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling o1 is a Kling image model for text-to-image generation and image editing with strong semantic understanding and reference-image consistency."}', 'Kling o1 is a Kling image model for text-to-image generation and image editing with strong semantic understanding and reference-image consistency.', 'active'),
(@xiaoma_id, 'sora-2', 'Sora-2 Official', 'video', 'image_to_video', 'sora-2', 'sora-2', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 4000, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Image-to-video","Stable"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["duration","orientation","input_reference","aspect_ratio","size","seconds","watermark","private"],"supported_ratios":["4","8","12","16:9","9:16"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"sora-2 is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'sora-2 is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'kwvideo-v2-ref', 'SD 2.0 Reference-to-Video', 'video', 'image_to_video', 'kwvideo-v2-ref', 'kwvideo-v2-ref', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3999, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Image-to-video","Video with audio","Reference-to-Videovideo","Seedream","720p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["version","duration","aspect_ratio","resolution","images"],"supported_ratios":["auto","4","5","6","7","8","9","10","11","12","13","14","15","adaptive","16:9","4:3"],"supported_qualities":["480p","720p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"kwvideo-v2-ref is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'kwvideo-v2-ref is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'doubao-seedance-1-5-pro-251215', 'Seedream 3.5 Pro', 'video', 'first_last_frame_video', 'doubao-seedance-1-5-pro-251215', 'doubao-seedance-1-5-pro-251215', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3998, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","First-frame reference","First/last frames","Video with audio","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["images","audio_duration","resolution","ratio","generate_audio"],"supported_ratios":["4","8","12","adaptive","16:9","9:16","1:1","3:4","4:3"],"supported_qualities":["480p","720p","1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Seedream 3.5 Pro is a ByteDance Seedance video model for high-quality video generation with sound, motion, and reference-frame control."}', 'Seedream 3.5 Pro is a ByteDance Seedance video model for high-quality video generation with sound, motion, and reference-frame control.', 'active'),
(@xiaoma_id, 'grok-video-3', 'grok-video-3', 'video', 'image_to_video', 'grok-video-3', 'grok-video-3', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3997, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Image-to-video","First-frame reference","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","images","aspect_ratio","size","duration"],"supported_ratios":["2:3","3:2","1:1","6","10"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"grok-video-3 is a Grok video generation model for fast image-to-video and text-to-video creation with short-video friendly durations and aspect ratios."}', 'grok-video-3 is a Grok video generation model for fast image-to-video and text-to-video creation with short-video friendly durations and aspect ratios.', 'active'),
(@xiaoma_id, 'kling-v3-omni-cankao', 'Kling-Omni Reference-to-Video', 'video', 'image_to_video', 'kling-v3-omni-cankao', 'kling-v3-omni-cankao', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3996, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Image-to-video","Video with audio","Reference-to-Videovideo","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["duration","images","prompt","mode","aspect_ratio"],"supported_ratios":["5","10","15","16:9","9:16","1:1"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-Omni Reference-to-Video is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-Omni Reference-to-Video is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'happyhorse-r2v', 'HappyHorse-Reference-to-Video', 'video', 'text_to_video', 'happyhorse-r2v', 'happyhorse-r2v', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3995, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","images","resolution","duration","ratio","aspect_ratio"],"supported_ratios":["3","4","5","6","7","8","9","10","11","12","13","14","15","16:9","9:16","3:4"],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"HappyHorse-Reference-to-Video is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode."}', 'HappyHorse-Reference-to-Video is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode.', 'active'),
(@xiaoma_id, 'kwvideo-v2-quannengcankao', 'SD 2.0 All-purpose Reference', 'video', 'image_to_video', 'kwvideo-v2-quannengcankao', 'kwvideo-v2-quannengcankao', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3994, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["_quan_neng_mode","duration","aspect_ratio","resolution","image_url","video_url","audio_url"],"supported_ratios":["auto","4","5","6","7","8","9","10","11","12","13","14","15","adaptive","16:9","4:3"],"supported_qualities":["480p","720p","1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"kwvideo-v2-quannengcankao is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'kwvideo-v2-quannengcankao is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'veo3.1', 'veo3.1', 'video', 'first_last_frame_video', 'veo3.1', 'veo3.1', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3993, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","First-frame reference","First/last frames","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","generation_mode","aspect_ratio","images","enhance_prompt","enable_upsample","duration","generation_type","quality"],"supported_ratios":["fast","null","pro","components","9:16","16:9","8","TEXT","REFERENCE","FIRST&LAST"],"supported_qualities":["1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"veo3.1 is a Google Veo video generation model with strong camera-control, first/last-frame guidance, and high-quality cinematic output."}', 'veo3.1 is a Google Veo video generation model with strong camera-control, first/last-frame guidance, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'omni-flash', 'omni-flash', 'video', 'image_to_video', 'omni-flash', 'omni-flash', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3992, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Reference-to-video","Multi-image reference","Audio video","6/8/10s","Google Gemini"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","images","aspect_ratio","duration","enhance_prompt","enable_upsample"],"supported_ratios":["16:9","9:16","6","8","10"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Gemini Omni Flash is Google''s multimodal AI video model. Supports text-to-video and multi-image reference-to-video, understands real-world physics, and generates high-definition short videos with audio. Generate from text alone, or upload 1-3 reference images to guide characters / objects / scene style. Supports 16:9 / 9:16 aspect ratios and 6 / 8 / 10 second durations."}', 'Gemini Omni Flash is Google''s multimodal AI video model. Supports text-to-video and multi-image reference-to-video, understands real-world physics, and generates high-definition short videos with audio. Generate from text alone, or upload 1', 'active'),
(@xiaoma_id, 'kwvideo-v2', 'SD 2.0 First/Last Frames', 'video', 'first_last_frame_video', 'kwvideo-v2', 'kwvideo-v2', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3991, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","Video with audio","First/last frames","Seedream","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["version","duration","aspect_ratio","resolution","images"],"supported_ratios":["auto","4","5","6","7","8","9","10","11","12","13","14","15","adaptive","16:9","4:3"],"supported_qualities":["480p","720p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"kwvideo-v2 is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'kwvideo-v2 is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'veo3.1-4k', 'veo3.1-4KHD', 'video', 'first_last_frame_video', 'veo3.1-4k', 'veo3.1-4k', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3990, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","First-frame reference","First/last frames","4K","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","generation_mode","aspect_ratio","images","enhance_prompt","enable_upsample","duration","generation_type","quality"],"supported_ratios":["fast","null","pro","components","9:16","16:9","8","TEXT","REFERENCE","FIRST&LAST"],"supported_qualities":["4k"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"veo3.1-4KHD is a Google Veo video generation model with strong camera-control, first/last-frame guidance, and high-quality cinematic output."}', 'veo3.1-4KHD is a Google Veo video generation model with strong camera-control, first/last-frame guidance, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'happyhorse-video-edit', 'HappyHorse-Video Editing', 'video', 'video_edit', 'happyhorse-video-edit', 'happyhorse-video-edit', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3989, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["video_edit"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","video","images","resolution","audio_setting","watermark"],"supported_ratios":[],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"HappyHorse-Video Editing is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode."}', 'HappyHorse-Video Editing is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode.', 'active'),
(@xiaoma_id, 'viduq3-cankaosheng', 'Vidu Q3 Reference-to-Video', 'video', 'image_to_video', 'viduq3-cankaosheng', 'viduq3-cankaosheng', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3988, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["model_version","images","resolution","duration","aspect_ratio","watermark","off_peak"],"supported_ratios":["4","8","12","16","auto","16:9","9:16","4:3","3:4","1:1"],"supported_qualities":["720p","1080p","540p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Vidu Q3 Reference-to-Video is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output."}', 'Vidu Q3 Reference-to-Video is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output.', 'active'),
(@xiaoma_id, 'viduq3', 'Vidu Q3', 'video', 'first_last_frame_video', 'viduq3', 'viduq3', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3987, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","First-frame reference","First/last frames","Video with audio","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["images","model_variant","resolution","duration","aspect_ratio","off_peak"],"supported_ratios":["4","8","12","16","16:9","9:16","4:3","3:4","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Vidu Q3 is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output."}', 'Vidu Q3 is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output.', 'active'),
(@xiaoma_id, 'happyhorse-t2v', 'HappyHorse-Text-to-video', 'video', 'text_to_video', 'happyhorse-t2v', 'happyhorse-t2v', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3986, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","resolution","ratio","duration"],"supported_ratios":["16:9","9:16","1:1","4:3","3:4","3","4","5","6","7","8","9","10","11","12","13"],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"HappyHorse-Text-to-video is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode."}', 'HappyHorse-Text-to-video is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode.', 'active'),
(@xiaoma_id, 'pixverse-v6-shouweizhen', 'Pix V6 First/Last Frames', 'video', 'first_last_frame_video', 'pixverse-v6-shouweizhen', 'pixverse-v6-shouweizhen', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3985, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","Video with audio","First/last frames","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["resolution","duration","images","aspect_ratio"],"supported_ratios":["3","6","9","12","15","16:9","4:3","1:1","3:4","9:16","3:2","2:3","21:9"],"supported_qualities":["360P","540P","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"pixverse-v6-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'pixverse-v6-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'vidu-mv', 'VIDU-Music MV', 'video', 'image_to_video', 'vidu-mv', 'vidu-mv', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3984, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["images","audio_url","resolution","lip_ref_url","lip_sync","aspect_ratio","style","add_subtitle","prompt","duration"],"supported_ratios":["16:9","9:16","1:1","4:3","3:4"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"VIDU-Music MV is a Vidu music video model that generates narrated or music-driven videos from audio and reference images, billed by actual duration."}', 'VIDU-Music MV is a Vidu music video model that generates narrated or music-driven videos from audio and reference images, billed by actual duration.', 'active'),
(@xiaoma_id, 'happyhorse-i2v', 'HappyHorse-First Frame', 'video', 'image_to_video', 'happyhorse-i2v', 'happyhorse-i2v', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3983, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","images","_first_frame_url","resolution","duration"],"supported_ratios":["3","4","5","6","7","8","9","10","11","12","13","14","15"],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"HappyHorse-First Frame is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode."}', 'HappyHorse-First Frame is an Alibaba Bailian HappyHorse video model for text-to-video, image-to-video, reference-based generation, or video editing depending on the mode.', 'active'),
(@xiaoma_id, 'kling-motion-control-v3', 'Kling-Motion Control V3', 'video', 'video_edit', 'kling-motion-control-v3', 'kling-motion-control-v3', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3982, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","video_edit"],"tags":["Motion Control","videoGenerate ","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","image_url","video_url","keep_original_sound","character_orientation","mode"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-Motion Control V3 is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-Motion Control V3 is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'wan2.6-cankaosheng', 'Wanxiang 2.6 Reference-to-Video', 'video', 'image_to_video', 'wan2.6-cankaosheng', 'wan2.6-cankaosheng', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3981, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"tags":["Reference-to-Videovideo","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","reference_urls","quality","resolution","aspect_ratio","duration","shot_type"],"supported_ratios":["16:9","9:16","1:1","4:3","3:4","2","4","6","8","10"],"supported_qualities":["fast","standard","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Wanxiang 2.6 Reference-to-Video is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation."}', 'Wanxiang 2.6 Reference-to-Video is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation.', 'active'),
(@xiaoma_id, 'kling-v3-omni-shouweizhen', 'Kling-Omni First/Last Frames', 'video', 'first_last_frame_video', 'kling-v3-omni-shouweizhen', 'kling-v3-omni-shouweizhen', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3980, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video","first_last_frame_video"],"tags":["Image-to-video","Video with audio","First/last frames","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["duration","images","prompt","mode"],"supported_ratios":["5","10","15"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"kling-v3-omni-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'kling-v3-omni-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'pixverse-c1-cankaosheng', 'Pix C1 Reference-to-Video', 'video', 'image_to_video', 'pixverse-c1-cankaosheng', 'pixverse-c1-cankaosheng', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3979, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["resolution","duration","aspect_ratio","images"],"supported_ratios":["3","6","9","12","15","16:9","9:16","1:1","3:4","4:3","3:2","2:3","21:9"],"supported_qualities":["360P","540P","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Pix C1 Reference-to-Video is a PixVerse video generation model for text-to-video, image-to-video, reference-based generation, and dynamic short-video creation."}', 'Pix C1 Reference-to-Video is a PixVerse video generation model for text-to-video, image-to-video, reference-based generation, and dynamic short-video creation.', 'active'),
(@xiaoma_id, 'kling-v3-omni-videoref', 'Kling-Omni Video Reference', 'video', 'video_edit', 'kling-v3-omni-videoref', 'kling-v3-omni-videoref', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3978, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video","video_edit"],"tags":["Video Reference","Video Editing","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["duration","images","video","refer_type","keep_original_sound","prompt","mode","aspect_ratio"],"supported_ratios":["5","10","16:9","9:16","1:1"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-Omni Video Reference is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-Omni Video Reference is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'kling-v3-video', 'Kling-V3-video', 'video', 'first_last_frame_video', 'kling-v3-video', 'kling-v3-video', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3977, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","Video with audio","First/last frames","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["duration","images","prompt","mode","aspect_ratio"],"supported_ratios":["5","10","15","16:9","9:16","1:1"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-V3-video is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-V3-video is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'wan2.7-cankaosheng', 'Wanxiang 2.7 Reference-to-Video', 'video', 'image_to_video', 'wan2.7-cankaosheng', 'wan2.7-cankaosheng', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3976, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Reference-to-Videovideo","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","reference_urls","reference_video","resolution","duration","prompt_extend","ratio","_mode"],"supported_ratios":["3","6","9","12","15","16:9","9:16","1:1","4:3","3:4"],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Wanxiang 2.7 Reference-to-Video is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation."}', 'Wanxiang 2.7 Reference-to-Video is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation.', 'active'),
(@xiaoma_id, 'kling-motion-control', 'Kling-Motion Control', 'video', 'video_edit', 'kling-motion-control', 'kling-motion-control', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3975, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","video_edit"],"tags":["Motion Control","videoGenerate "],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","image_url","video_url","keep_original_sound","character_orientation","mode"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-Motion Control is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling-Motion Control is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'wan2.2-animate-mix', 'Wanxiang-Video Face Swap', 'video', 'video_edit', 'wan2.2-animate-mix', 'wan2.2-animate-mix', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3974, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","video_edit"],"tags":["Video Face Swap"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["image_url","video_url","mode"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Wanxiang-Video Face Swap is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation."}', 'Wanxiang-Video Face Swap is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation.', 'active'),
(@xiaoma_id, 'kling-avatar-image2video', 'Kling-Digital Human', 'video', 'video_edit', 'kling-avatar-image2video', 'kling-avatar-image2video', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3973, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","video_edit"],"tags":["Digital Human","videoGenerate "],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["image","sound_file","prompt","mode"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling-Digital Human is a Kling image model for text-to-image generation and image editing with strong semantic understanding and reference-image consistency."}', 'Kling-Digital Human is a Kling image model for text-to-image generation and image editing with strong semantic understanding and reference-image consistency.', 'active'),
(@xiaoma_id, 'viduq2-cankaosheng', 'Vidu Q2 Reference-to-Video', 'video', 'image_to_video', 'viduq2-cankaosheng', 'viduq2-cankaosheng', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3972, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video"],"tags":["Reference-to-Videovideo","1080p","HD","Video with audio"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["images","resolution","duration","aspect_ratio"],"supported_ratios":["5","10","16:9","9:16","4:3","3:4","1:1"],"supported_qualities":["540p","720p","1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Vidu Q2 Reference-to-Video is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output."}', 'Vidu Q2 Reference-to-Video is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output.', 'active'),
(@xiaoma_id, 'vidu-jieshuoman', 'VIDU-Narrated Comic', 'video', 'text_to_video', 'vidu-jieshuoman', 'vidu-jieshuoman', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3971, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["script_name","script_content","assets","duration","resolution","aspect_ratio","style","language","tts_speed","enable_lipsync"],"supported_ratios":["16:9","9:16","4:3","3:4"],"supported_qualities":["720p","1080p"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"VIDU-Narrated Comic is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output."}', 'VIDU-Narrated Comic is a Vidu video model for text-to-video, image-to-video, reference-based generation, character consistency, and audio-synchronized video output.', 'active'),
(@xiaoma_id, 'wan2.6-shouzheng', 'Wanxiang 2.6 First Frame', 'video', 'image_to_video', 'wan2.6-shouzheng', 'wan2.6-shouzheng', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3970, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Image-to-video","Text-to-video","Video with audio","1080p","First-frame reference","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","img_url","audio_url","quality","resolution","aspect_ratio","duration","shot_type","prompt_extend"],"supported_ratios":["16:9","9:16","1:1","4:3","3:4","3","6","9","12","15"],"supported_qualities":["fast","standard","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Wanxiang 2.6 First Frame is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation."}', 'Wanxiang 2.6 First Frame is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation.', 'active'),
(@xiaoma_id, 'kling-v2-6', 'Kling 2.6 Pro', 'video', 'image_to_video', 'kling-v2-6', 'kling-v2-6', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3969, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Image-to-video","Video with audio","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["duration","images","prompt","negative_prompt","sound","aspect_ratio"],"supported_ratios":["5","10","16:9","9:16","1:1"],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Kling 2.6 Pro is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output."}', 'Kling 2.6 Pro is a Kling video generation model for text-to-video, image-to-video, reference-based video, motion control, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'wan2.7-shouweizhen', 'Wanxiang 2.7 First/Last Frames', 'video', 'first_last_frame_video', 'wan2.7-shouweizhen', 'wan2.7-shouweizhen', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3968, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video","first_last_frame_video"],"tags":["Image-to-video","First/last frames","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","images","resolution","duration","prompt_extend"],"supported_ratios":["3","6","9","12","15"],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"wan2.7-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'wan2.7-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'pixverse-v5.6-r2v', 'Pix V5.6 Reference-to-Video', 'video', 'text_to_video', 'pixverse-v5.6-r2v', 'pixverse-v5.6-r2v', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3967, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","images","resolution","duration","aspect_ratio"],"supported_ratios":["5","8","10","16:9","4:3","1:1","3:4","9:16"],"supported_qualities":["360P","540P","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Pix V5.6 Reference-to-Video is a PixVerse video generation model for text-to-video, image-to-video, reference-based generation, and dynamic short-video creation."}', 'Pix V5.6 Reference-to-Video is a PixVerse video generation model for text-to-video, image-to-video, reference-based generation, and dynamic short-video creation.', 'active'),
(@xiaoma_id, 'veo3.1-lite', 'veo3.1-lite', 'video', 'first_last_frame_video', 'veo3.1-lite', 'veo3.1-lite', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3966, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","First/last frames","SD/4K"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","quality","aspect_ratio","images","enhance_prompt"],"supported_ratios":["9:16","16:9"],"supported_qualities":["sd","4k"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"veo3.1-lite is a Google Veo video generation model with strong camera-control, first/last-frame guidance, and high-quality cinematic output."}', 'veo3.1-lite is a Google Veo video generation model with strong camera-control, first/last-frame guidance, and high-quality cinematic output.', 'active'),
(@xiaoma_id, 'pixverse-v5.6-shouweizhen', 'Pix V5.6 First/Last Frames', 'video', 'first_last_frame_video', 'pixverse-v5.6-shouweizhen', 'pixverse-v5.6-shouweizhen', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3965, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video","first_last_frame_video"],"tags":["Text-to-video","Image-to-video","Video with audio","First/last frames","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["resolution","duration","images","aspect_ratio"],"supported_ratios":["5","8","10","16:9","4:3","1:1","3:4","9:16"],"supported_qualities":["360P","540P","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"pixverse-v5.6-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'pixverse-v5.6-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'pixverse-c1-shouweizhen', 'Pix C1 First/Last Frames', 'video', 'first_last_frame_video', 'pixverse-c1-shouweizhen', 'pixverse-c1-shouweizhen', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3964, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["image_to_video","first_last_frame_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["resolution","duration","images"],"supported_ratios":["3","6","9","12","15"],"supported_qualities":["360P","540P","720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"pixverse-c1-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows."}', 'pixverse-c1-shouweizhen is an AI video model for text-to-video, image-to-video, reference generation, or video editing workflows.', 'active'),
(@xiaoma_id, 'wan2.7-xuxie', 'Wanxiang 2.7 Video Extension', 'video', 'text_to_video', 'wan2.7-xuxie', 'wan2.7-xuxie', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3963, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video"],"tags":["AI feature"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["prompt","clips","resolution","duration","prompt_extend"],"supported_ratios":["3","6","9","12","15"],"supported_qualities":["720P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Wanxiang 2.7 Video Extension is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation."}', 'Wanxiang 2.7 Video Extension is an Alibaba Tongyi Wanxiang video model for text-to-video, image-to-video, reference-based generation, and cinematic video creation.', 'active'),
(@xiaoma_id, 'hailuo-2.3', 'Hailuo 2.3', 'video', 'image_to_video', 'hailuo-2.3', 'hailuo-2.3', 1, 600, 3, 1000, 0, 0, 5, 0, 20, 0, 3962, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_to_video","image_to_video"],"tags":["Text-to-video","Image-to-video","1080p","HD"],"default_params":{"duration":"5s","aspect_ratio":"16:9","resolution":"720p"},"param_names":["model_version","duration","resolution","enhance_prompt","prompt"],"supported_ratios":["6","10"],"supported_qualities":["768P","1080P"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Hailuo 2.3 is a MiniMax Hailuo creative model for speech, music, or video generation depending on the selected workflow."}', 'Hailuo 2.3 is a MiniMax Hailuo creative model for speech, music, or video generation depending on the selected workflow.', 'active'),
(@xiaoma_id, 'speech-2.8', 'Hailuo Voice Clone 2.8', 'audio', 'audio_generation', 'speech-2.8', 'speech-2.8', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 3000, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Voice cloning","Text-to-speech","Voice cloning","Multilingual"],"default_params":{"format":"mp3"},"param_names":["speed","pitch","emotion","sound_effects","quality"],"supported_ratios":[],"supported_qualities":["turbo","hd"],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Hailuo Voice Clone 2.8 is a speech synthesis model with high-quality voices, multilingual support, emotion control, and long-text narration support."}', 'Hailuo Voice Clone 2.8 is a speech synthesis model with high-quality voices, multilingual support, emotion control, and long-text narration support.', 'active'),
(@xiaoma_id, 'music-2.5+', 'Hailuo Music Generation 2.5+', 'audio', 'audio_generation', 'music-2.5+', 'music-2.5+', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 2999, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Music generation","Lyrics generation","AI composition","Instrumental music"],"default_params":{"format":"mp3"},"param_names":["lyrics","is_instrumental","sample_rate","bitrate"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"music-2.5+ is an AI music generation model for creating songs or instrumental music from lyrics and style prompts."}', 'music-2.5+ is an AI music generation model for creating songs or instrumental music from lyrics and style prompts.', 'active'),
(@xiaoma_id, 'suno-v4.5', 'Suno Music Generation 4.5', 'audio', 'audio_generation', 'suno-v4.5', 'suno-v4.5', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 2998, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Music generation","AI composition","Lyric continuation","Karaoke subtitles","Suno V4.5"],"default_params":{"format":"mp3"},"param_names":["mv","make_instrumental","vocal_gender","sample_rate","bitrate"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Suno V4.5 (chirp-auk) is a music generation model that creates complete vocal songs from lyrics and a style description. It supports instrumental music, lyric continuation, and karaoke subtitles. Songs can be up to 4 minutes long and can be generated in as fast as 80 seconds."}', 'Suno V4.5 (chirp-auk) is a music generation model that creates complete vocal songs from lyrics and a style description. It supports instrumental music, lyric continuation, and karaoke subtitles. Songs can be up to 4 minutes long and can be', 'active'),
(@xiaoma_id, 'music-2.5', 'Hailuo Music Generation 2.5', 'audio', 'audio_generation', 'music-2.5', 'music-2.5', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 2997, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Music generation","Lyrics generation","AI composition"],"default_params":{"format":"mp3"},"param_names":["lyrics","is_instrumental","sample_rate","bitrate"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"music-2.5 is an AI music generation model for creating songs or instrumental music from lyrics and style prompts."}', 'music-2.5 is an AI music generation model for creating songs or instrumental music from lyrics and style prompts.', 'active'),
(@xiaoma_id, 'doubao-tts-2.0', 'Doubao TTS 2.0', 'audio', 'audio_generation', 'doubao-tts-2.0', 'doubao-tts-2.0', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 2996, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Text-to-speech","Multiple voices","Multiple emotions","Multilingual"],"default_params":{"format":"mp3"},"param_names":["speech_rate","emotion","emotion_scale","format"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"doubao-tts-2.0 is a text-to-speech model with multiple voices, multilingual support, and natural speech output."}', 'doubao-tts-2.0 is a text-to-speech model with multiple voices, multilingual support, and natural speech output.', 'active'),
(@xiaoma_id, 'gemini-3.1-flash-tts-preview', 'Gemini-3.1-TTS', 'audio', 'audio_generation', 'gemini-3.1-flash-tts-preview', 'gemini-3.1-flash-tts-preview', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 2995, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Text-to-speech","Multiple voices","Multilingual"],"default_params":{"format":"mp3"},"param_names":[],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Gemini-3.1-TTS is a native Google Gemini text-to-speech model with multiple voices, multilingual support, and natural emotional delivery."}', 'Gemini-3.1-TTS is a native Google Gemini text-to-speech model with multiple voices, multilingual support, and natural emotional delivery.', 'active'),
(@xiaoma_id, 'gemini-2.5-pro-preview-tts', 'Gemini-2.5-TTS', 'audio', 'audio_generation', 'gemini-2.5-pro-preview-tts', 'gemini-2.5-pro-preview-tts', 1, 300, 3, 1000, 0, 0, 5, 0, 10, 0, 2994, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["audio_generation"],"tags":["Text-to-speech","Multiple voices","Multilingual"],"default_params":{"format":"mp3"},"param_names":["model_version"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/media/generate","query":"/v1/media/status?task_id={task_id}"},"api_format":"xiaoma_media","description":"Gemini-2.5-TTS is a native Google Gemini text-to-speech model with multiple voices, multilingual support, and natural emotional delivery."}', 'Gemini-2.5-TTS is a native Google Gemini text-to-speech model with multiple voices, multilingual support, and natural emotional delivery.', 'active'),
(@xiaoma_id, 'gemini-3.5-flash', 'Gemini 3.5 flash', 'text', 'text_generation', 'gemini-3.5-flash', 'gemini-3.5-flash', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 2000, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation"],"tags":["多轮对话","多模态","深度思考","长上下文","联网搜索","极速","哈基米"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search","enable_thinking"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1beta/models/{model}:generateContent"},"api_format":"gemini","description":"Gemini 3.5 Flash is now generally available (GA). It is Google’s smartest lightweight, high-speed model, stable enough for large-scale production use and leading in agent execution, coding, and long-running task performance."}', 'Gemini 3.5 Flash is now generally available (GA). It is Google’s smartest lightweight, high-speed model, stable enough for large-scale production use and leading in agent execution, coding, and long-running task performance.', 'active'),
(@xiaoma_id, 'gpt-5.4', 'GPT-5.4', 'text', 'text_generation', 'gpt-5.4', 'gpt-5.4', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1999, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Multi-turn chat","Multimodal","Deep thinking","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","enable_thinking","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/chat/completions"},"api_format":"openai","description":"GPT-5.4 is an OpenAI multimodal language model for high-quality chat, reasoning, coding, creative writing, and professional task solving."}', 'GPT-5.4 is an OpenAI multimodal language model for high-quality chat, reasoning, coding, creative writing, and professional task solving.', 'active'),
(@xiaoma_id, 'gpt-5.5', 'GPT-5.5', 'text', 'text_generation', 'gpt-5.5', 'gpt-5.5', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1998, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation"],"tags":["Multi-turn chat","Multimodal","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/chat/completions"},"api_format":"openai","description":"GPT-5.5 is an OpenAI multimodal language model for high-quality chat, reasoning, coding, creative writing, and professional task solving."}', 'GPT-5.5 is an OpenAI multimodal language model for high-quality chat, reasoning, coding, creative writing, and professional task solving.', 'active'),
(@xiaoma_id, 'gemini-3.1-pro-preview', 'Gemini 3.1 Pro', 'text', 'text_generation', 'gemini-3.1-pro-preview', 'gemini-3.1-pro-preview', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1997, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Multi-turn chat","Multimodal","Deep thinking","Long context","Web search","Hakimi"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search","enable_thinking"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1beta/models/{model}:generateContent"},"api_format":"gemini","description":"Gemini 3.1 Pro is a Google Gemini multimodal model for reasoning, long-context analysis, document processing, and real-time productivity tasks."}', 'Gemini 3.1 Pro is a Google Gemini multimodal model for reasoning, long-context analysis, document processing, and real-time productivity tasks.', 'active'),
(@xiaoma_id, 'claude-opus-4-7', 'opus-4-7', 'text', 'text_generation', 'claude-opus-4-7', 'claude-opus-4-7', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1996, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Coding","Deep thinking","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","enable_thinking","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/messages"},"api_format":"anthropic","description":"opus-4-7 is a Claude model for complex reasoning, coding, long-form writing, structured analysis, and safe assistant-style collaboration."}', 'opus-4-7 is a Claude model for complex reasoning, coding, long-form writing, structured analysis, and safe assistant-style collaboration.', 'active'),
(@xiaoma_id, 'gpt-5.5-xhigh', 'GPT-5.5 Deep Reasoning', 'text', 'text_generation', 'gpt-5.5-xhigh', 'gpt-5.5-xhigh', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1995, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation"],"tags":["Multi-turn chat","Multimodal","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/chat/completions"},"api_format":"openai","description":"gpt-5.5-xhigh is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows."}', 'gpt-5.5-xhigh is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows.', 'active'),
(@xiaoma_id, 'gpt-5.5-high', 'GPT-5.5 High Reasoning', 'text', 'text_generation', 'gpt-5.5-high', 'gpt-5.5-high', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1994, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation"],"tags":["Multi-turn chat","Multimodal","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/chat/completions"},"api_format":"openai","description":"gpt-5.5-high is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows."}', 'gpt-5.5-high is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows.', 'active'),
(@xiaoma_id, 'gemini-3-pro-preview', 'Gemini 3 Pro', 'text', 'text_generation', 'gemini-3-pro-preview', 'gemini-3-pro-preview', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1993, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Multi-turn chat","Multimodal","Deep thinking","Long context","Web search","Hakimi"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","enable_thinking","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1beta/models/{model}:generateContent"},"api_format":"gemini","description":"Gemini 3 Pro is a Google Gemini multimodal model for reasoning, long-context analysis, document processing, and real-time productivity tasks."}', 'Gemini 3 Pro is a Google Gemini multimodal model for reasoning, long-context analysis, document processing, and real-time productivity tasks.', 'active'),
(@xiaoma_id, 'claude-sonnet-4-6', 'sonnet-4-6', 'text', 'text_generation', 'claude-sonnet-4-6', 'claude-sonnet-4-6', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1992, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Coding","Deep thinking","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search","enable_thinking"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/messages"},"api_format":"anthropic","description":"sonnet-4-6 is a Claude model for complex reasoning, coding, long-form writing, structured analysis, and safe assistant-style collaboration."}', 'sonnet-4-6 is a Claude model for complex reasoning, coding, long-form writing, structured analysis, and safe assistant-style collaboration.', 'active'),
(@xiaoma_id, 'claude-opus-4-6', 'opus-4-6', 'text', 'text_generation', 'claude-opus-4-6', 'claude-opus-4-6', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1991, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Coding","Deep thinking","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","enable_thinking","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/messages"},"api_format":"anthropic","description":"opus-4-6 is a Claude model for complex reasoning, coding, long-form writing, structured analysis, and safe assistant-style collaboration."}', 'opus-4-6 is a Claude model for complex reasoning, coding, long-form writing, structured analysis, and safe assistant-style collaboration.', 'active'),
(@xiaoma_id, 'gpt-5.4-xhigh', 'GPT-5.4 Deep Reasoning', 'text', 'text_generation', 'gpt-5.4-xhigh', 'gpt-5.4-xhigh', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1990, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Multi-turn chat","Multimodal","Deep thinking","Long context","Web search"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","web_search","enable_thinking"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/chat/completions"},"api_format":"openai","description":"gpt-5.4-xhigh is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows."}', 'gpt-5.4-xhigh is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows.', 'active'),
(@xiaoma_id, 'gpt-5.2-chat-latest', 'GPT-5.2 Chat', 'text', 'text_generation', 'gpt-5.2-chat-latest', 'gpt-5.2-chat-latest', 0, 120, 3, 1000, 0, 0, 5, 0, 1, 0, 1989, '{"source":"xiaoma_api_docs","source_checked_at":"2026-05-31","capabilities":["text_chat","text_generation","prompt_optimize"],"tags":["Multi-turn chat","Multimodal","Deep thinking","Long context","Web search","gpt"],"default_params":{"temperature":0.7,"max_tokens":1024},"param_names":["attachments","enable_thinking","web_search"],"supported_ratios":[],"supported_qualities":[],"endpoints":{"create":"/v1/chat/completions"},"api_format":"openai","description":"gpt-5.2-chat-latest is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows."}', 'gpt-5.2-chat-latest is an AI model for chat, reasoning, coding, multimodal understanding, and productivity workflows.', 'active');

UPDATE ai_models m
JOIN tmp_xiaoma_api_models s
  ON s.provider_id = m.provider_id
 AND s.api_model_name COLLATE utf8mb4_unicode_ci = m.api_model_name COLLATE utf8mb4_unicode_ci
 AND m.deleted_at IS NULL
   SET m.name = s.name,
       m.display_name = s.display_name,
       m.model_type = s.model_type,
       m.sub_type = s.sub_type,
       m.upstream_model_code = s.upstream_model_code,
       m.is_async = s.is_async,
       m.timeout_seconds = s.timeout_seconds,
       m.retry_times = s.retry_times,
       m.retry_delay_ms = s.retry_delay_ms,
       m.max_concurrency = s.max_concurrency,
       m.sort_order = s.sort_order,
       m.config = s.config_json,
       m.remark = s.remark,
       m.updated_at = NOW(3);

INSERT INTO ai_models
(provider_id, name, display_name, model_type, sub_type, api_model_name, upstream_model_code, is_async, query_task_url, request_template, result_path, status_mapping, error_mapping, timeout_seconds, retry_times, retry_delay_ms, daily_limit, daily_limit_per_user, max_concurrency, priority, points_cost, api_cost_cents, sort_order, config, remark, status, created_at, updated_at)
SELECT s.provider_id, s.name, s.display_name, s.model_type, s.sub_type, s.api_model_name, s.upstream_model_code, s.is_async,
       '', '{}', '', '{}', '{}', s.timeout_seconds, s.retry_times, s.retry_delay_ms, s.daily_limit, s.daily_limit_per_user,
       s.max_concurrency, s.priority, s.points_cost, s.api_cost_cents, s.sort_order, s.config_json, s.remark, s.status, NOW(3), NOW(3)
  FROM tmp_xiaoma_api_models s
 WHERE NOT EXISTS (
   SELECT 1 FROM ai_models m
    WHERE m.provider_id = s.provider_id
      AND m.api_model_name COLLATE utf8mb4_unicode_ci = s.api_model_name COLLATE utf8mb4_unicode_ci
      AND m.deleted_at IS NULL
 );

DROP TEMPORARY TABLE IF EXISTS tmp_xiaoma_api_models;
